### ISSUE TITLE
Define & Document Enum Types in Eluna

### ISSUE THREAD

**Issue by Patman64** [ElunaLuaEngine/Eluna#104]
We have two issues with _enum_ values:
- They aren't available in Lua code.
- They aren't documented.

So I have an idea for solving both problems. Inside `extensions/Enums.ext` we would have all the enums defined with a structure similar to the following:

``` lua
--[[
    The mask bits for the different "school" types
    (e.g. fire, frost, etc.) of spells.
]]
SpellSchoolMask = {
    NONE = 0,  -- This comment is for the NONE value.
    NORMAL = 1,
    HOLY = 2,
    FIRE = 4,
    NATURE = 8,  -- #mangos That tagged this as only available on MaNGOS.
    FROST = 16,  -- #trinity That tagged this as only available on TrinityCore.
    SHADOW = 32,  -- #no_classic That tagged this as not available on Classic.
    ARCANE = 64  -- #trinity #wotlk_only Tags can be combined.
}
```

I would have the documentation generator parse the file for the enums and generate their pages.

**Comment by Rochet2** [comment]
Current enum code:
http://pastebin.com/V29X34SD

Now includes all types used in documentation so far (enums in documentation with [enum] notation)
Also has some other enums in it that were originally seen either used by methods (undocumented) or that were seen useful.
