### ISSUE TITLE
Adding support of temporary spawn

### ISSUE THREAD

**Issue by Warkdev** [ElunaLuaEngine/Eluna#114]
Hello, to be an equivalent to SD2 scripting library, Eluna needs a way to support temporary spawn. Actually, when a mob is invoked within the game, it becomes a persistent NPC (until restart of the server) and has its own respawn time, and so on...

If we take t he basic escort case, ideally,  these NPC must be removed from the game when:

- They have been killed (customizable delay)
- They have killed the escorted NPC (customizable delay)

Another approach would be to provide an equivalent to ".npc del" command.

**Comment by Rochet2** [comment]
Im adding the documenation and closing this since no replies after multiple queries about issue being resolved.
If the issue was not resolved you can open a new ticket.
