### ISSUE TITLE
Adding BG Hooks/Methods to TC source

### ISSUE THREAD

**Issue by Foereaper** [ElunaLuaEngine/Eluna#115]
Added new BG stuff, needs to be added to TC:

https://github.com/ElunaLuaEngine/Eluna/commit/0bfdf632e760170d47aa6d818494835107bdafe6
https://github.com/ElunaLuaEngine/Eluna/commit/29385c63b19139f0b511022f62d20bb25e534e41
https://github.com/ElunaLuaEngine/Eluna/commit/731682708f46a57abd11c36dc6e253132c2b54cb

**Comment by Rochet2** [comment]
tc

**Comment by Salja** [comment]
Oh sorry i have think tu have already
