### ISSUE TITLE
[Suggestion] Unbind Instance All Player Function

### ISSUE THREAD

**Issue by Asandru** [ElunaLuaEngine/Eluna#134]
Here is the patch I wrote: http://pastebin.com/1eWTQx10
Due to some issues I can't pull request

**Comment by Patman64** [comment]
Would recommend the name `UnbindAllInstances` instead.

Also needs more work for Classic (`GetDifficulty` doesn't exist for example).

**Comment by Rochet2** [comment]
Added.
