### ISSUE TITLE
Calling a hook on game events

### ISSUE THREAD

**Issue by k59** [ElunaLuaEngine/Eluna#143]
There's often a lot of action going on with certain game events, from Christmas, Halloween, Day/Night or even custom game events, from what I can see there currently is no hooks that fires off with when an event ends or begins.

Personally I would have loved to have the option to tie hooks to _creatures_ when events _begin_ and _end_, ideally a game event hook could be tied in with any object, yet I don't know if it would have been preferable to handle this by individual hooks for each object component or with a generalized approach, such as sending the event to the map.

Just as a heads up; the _game_event_ system(via db) is present in both (C)MaNGOS and TrinityCore.

I hope this proposal covers a sufficiently good concept of the hook and I'd appreciate any feedback or input if you see holes/problems in the idea.

**Comment by Patman64** [comment]
Maybe it would be easier to just swap out the Creature with an identical one (but with different scripting) when the Game Event starts/stops?

**Comment by danielsreichenbach** [comment]
Creature behaviour would not be the only reason to support game event hooks. Game events in common would benefit from being handled by Eluna.

**Comment by Foereaper** [comment]
I recently made a patch for this for another user, I'll look it over and possibly add a hook in shortly

**Comment by k59** [comment]
@Foereaper that would be great!

**Comment by Rochet2** [comment]
Closing because implemented on TC and mangos.
For more see https://github.com/ElunaLuaEngine/Eluna/issues/226
