### ISSUE TITLE
TC compile error

### ISSUE THREAD

**Issue by denisakajacob** [ElunaLuaEngine/Eluna#154]
http://pastebin.com/Q4B2f1LT 
used: cmake ../ -DCMAKE_INSTALL_PREFIX=/home/wow/server -DLIBSDIR=/home/wow/server/lib -DTOOLS=1 -DWITH_WARNINGS=1 -DTOOLS=1
Rev TC: https://github.com/TrinityCore/TrinityCore/commit/0b1355b2800f8000dbf245cb035ac2bc9ba4a06e
please help

**Comment by Rochet2** [comment]
Related http://emudevs.com/showthread.php/4996-TC-compile-error
> We were over 100 commits behind so I updated now.

Try with https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/83157519813b68a80f0d480df6d9ee56f16a793e or newer

**Comment by Rochet2** [comment]
Any news?

**Comment by Rochet2** [comment]
guess not.
