### ISSUE TITLE
Cast mana free spells (without instant cast times)

### ISSUE THREAD

**Issue by fredriksa** [ElunaLuaEngine/Eluna#156]
More often than not spells uses mana percentages when casted by a mob. The only way to avoid this is of course to edit the spell.dbc file, but it would be quite neat to be able to specify what spells should and shouldn't cost mana. I've been in need for this for quite some time so would appreciate if one of you gents could implement this functionality!

**Comment by Rochet2** [comment]
Seems it is possible to do that on TC easily using `TriggerCastFlags` but on mangos based there is no such thing and no alternatives I can find.

**Comment by Freddan962** [comment]
Bummers, would have been a great feature to when working with content creation.
