### ISSUE TITLE
UINT32_MAX not declared in lmarshal.cpp

### ISSUE THREAD

**Issue by Jiinx** [ElunaLuaEngine/Eluna#161]
This error 
![Image of error](http://puu.sh/jl6IT/2f6ebe00a5.png)
occurs on fresh pull as of 7/31/15.

OS: Debian 7.8
Pull: https://github.com/ElunaLuaEngine/Eluna/commit/31470c2cf7b9724ce0d1267c38d2d2c5e6f2ca7b

**HACKFIX:**
Added 
````c++
#define UINT32_MAX ((uint32_t)-1)
````
to lmarshall.cpp

**Comment by Rochet2** [comment]
Try adding `#include <cstdint>`

**Comment by Rochet2** [comment]
Post back if still occurs
