### ISSUE TITLE
Merge conflict with fresh TrinityCore

### ISSUE THREAD

**Issue by kevinc123** [ElunaLuaEngine/Eluna#168]
Hello,when I download the trinitycore fresh and merge the eluna engine I get unmerged files

remote: Counting objects: 2811, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 2811 (delta 763), reused 760 (delta 760), pack-reused 2039
Receiving objects: 100% (2811/2811), 3.88 MiB | 1.71 MiB/s, done.
Resolving deltas: 100% (2020/2020), completed with 141 local objects.
From https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
* branch            HEAD       -> FETCH_HEAD

Auto-merging src/server/worldserver/CMakeLists.txt
CONFLICT (content): Merge conflict in src/server/worldserver/CMakeLists.txt
Auto-merging src/server/scripts/CMakeLists.txt
CONFLICT (content): Merge conflict in src/server/scripts/CMakeLists.txt
Auto-merging src/server/game/Miscellaneous/SharedDefines.h
Auto-merging src/server/game/Handlers/MiscHandler.cpp
Auto-merging src/server/game/Entities/Unit/Unit.cpp
Auto-merging src/server/game/Entities/Player/Player.cpp
Auto-merging src/server/game/CMakeLists.txt
CONFLICT (content): Merge conflict in src/server/game/CMakeLists.txt
Auto-merging src/CMakeLists.txt
CONFLICT (content): Merge conflict in src/CMakeLists.txt
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Rochet2** [comment]
To avoid such errors use this: https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md
If you merge with TC and keep on merging read this: https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/MERGING.md

Anyways the repo will be updated _soon_.

**Comment by Rochet2** [comment]
updated to support TC commit https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/f2aa95c3503fe936f08d9fcc3c7f76f8bfcd8b36
