### ISSUE TITLE
Found Error in ElunaErrors.log

### ISSUE THREAD

**Issue by abennette32** [ElunaLuaEngine/Eluna#169]
Found on Debian 8.1 ElunaMangosTbc

lua_scripts/extensions/ObjectVariables.ext:40: attempt to index global 'self' (a nil value)

Line 40 should be referencing "obj" instead of "self"

**Comment by Rochet2** [comment]
this was already fixed on https://github.com/ElunaLuaEngine/Eluna/commit/3cfa7ac575396325809fead6d8db740905b9e06c
but eluna version not yet updated to cores.
