### ISSUE TITLE
GameObject spawn hook & timed events

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#173]
Seems GameObject spawn hook might not be working properly with timed events.
http://emudevs.com/showthread.php/5048-Custom-hunter-trap-LUA-Script

Code below does not print onTimedEvent and onSummon is printed twice.

``` lua
local Trap = {}

function Trap.OnSummon(event, go)
    print("onSummon")
    go:RegisterEvent(Trap.Look, 1000, 0)
end

function Trap.Look(event, delay, pCall, go)
    print("onTimedEvent")
end

RegisterGameObjectEvent(164839, 2, Trap.OnSummon)
```

**Comment by drdread987** [comment]
Any luck with the bug or a work around?

**Comment by Rochet2** [comment]
Possibly fixed in https://github.com/ElunaLuaEngine/Eluna/commit/9aa048d78c3369437cd21690422c5fdb63fda735
