### ISSUE TITLE
Script-Created Taxi Returns Error

### ISSUE THREAD

**Issue by Valkryst** [ElunaLuaEngine/Eluna#177]
Hey,

This bug is being reported for a guy that I know on Skype, but I have seen it in-action. After following the example in the documentation, linked to below, the NPC defined as the Taxi-Master in the script, when clicked on as this is activated on Gossip Hello, returns the error "You are to far away from the taxi stand.".

I had buddy do a printout of the script-created path and it does exist, the script is essentially a copy-paste of the example below, and I have had him check out the DBC files to ensure that the script-created path doesn't conflict with any existing paths, which it doesn't.

http://eluna.emudevs.com/Global/AddTaxiPath.html

If you need more info, then you know where to find me. Typing this up around midnight, so if any of it doesn't make enough sense, just message.

**Comment by Rochet2** [comment]
Do you have the script?
Was he standing at the first coordinates of the flight path when starting it? (within some feet)

**Comment by Valkryst** [comment]
I'll have the script later tonight.

No, as far as I recall, the first flight-node was away from the NPC. I'm guessing you need to have the first flight-node be directly over the Flightmaster NPC for it to work correctly? (Didn't see anything about that in the documentation, I think...)

**Comment by Rochet2** [comment]
Yeah, that is the case. Need to have it where the flight starts at.

**Comment by Valkryst** [comment]
Gotcha. Looks like I'll be writing a tutorial on this at some point then. =P

**Comment by Rochet2** [comment]
PR to documentation? :)

**Comment by Valkryst** [comment]
Post a request for it? Might be a good idea, yeah. I'll pop open another issue with the request. :p

**Comment by Rochet2** [comment]
I meant PR, which is a Pull Request.
You can directly edit the source files in github: http://prntscr.com/9eyu4a
Do edits and submit them as a pull request on github.
Though I just now did this: https://github.com/ElunaLuaEngine/Eluna/commit/2bb387dcff95773b656bd6ba12dd12ba66dbc040
