### ISSUE TITLE
[Documentation] Taxi Paths

### ISSUE THREAD

**Issue by Valkryst** [ElunaLuaEngine/Eluna#178]
Hey,

If you take a look at the link below, there is absolutely no mention that the first node in the created taxi-path needs to be anywhere near the flight-master NPC nor any information on if the NPC requires any flight-master flags to be set.

It might be helpful to include more documentation than an out-of-place code sample.

http://eluna.emudevs.com/Global/AddTaxiPath.html

**Comment by Rochet2** [comment]
There are no creatures involved with the flying process or setting up paths other than the mounts.
Im rather sure they can be almost any creature (likely the model is only used and not the actual NPC)

Also regarding the path node thing read this reply of mine: https://github.com/ElunaLuaEngine/Eluna/issues/177#issuecomment-165214129

Do post below if you still wanted something added.
