### ISSUE TITLE
[Request] New Creature Event Hook

### ISSUE THREAD

**Issue by Valkryst** [ElunaLuaEngine/Eluna#179]
Hey,

Would it be possible to have a new Creature Event Hook (RegisterCreatureEvent/RegisterUniqueCreatureEvent) for the AI function MovementInform, so that we can do something whenever a creature stops movement.

Example:

Creature is told to move to location with :MoveTo(id, x, y, z), then, when the creature reaches it's destination, the hook fill fire off whatever function is registered to the event.

**Comment by Rochet2** [comment]
This is that hook
```
CREATURE_EVENT_ON_REACH_WP                        = 6,  // (event, creature, type, id)
```

**Comment by Valkryst** [comment]
It doesn't seem to work correctly as far as I can guess how to use it.

http://pastebin.com/76kbS4Cd

If you run this script, the NPC will walk to the location specified on line #36, then continuously/infinitely spam the lines on lines #47 & #48 without ever moving.

**Comment by Rochet2** [comment]
What is your Eluna version? On latest it works fine so I can only assume you are using an old version.

**Comment by Rochet2** [comment]
@Valkryst Any news?

**Comment by Valkryst** [comment]
Just asked Foe Reaper since I'm running the script on Harry's server. He said that you already know what's up with their version of Eluna and this was his main reply.

"No, due to custom changes it uses a localized version of the Lua engine, however no substantial updates to Eluna has been done post the localized version"

**Comment by Rochet2** [comment]
Im just going to close this because I know it is from an outdated version rather than an existing bug.
And seems you are not the maintainer of the source either so there is little you can do about it until the source you use is updated.
