### ISSUE TITLE
[compiler error] PlayerMethods.cpp

### ISSUE THREAD

**Issue by matuph** [ElunaLuaEngine/Eluna#182]
hello,
i heve a error PlayerMethods.cpp.
error is PlayerMethods.cpp (3952) "SendMovieStart" no element from "Player"

Tanks

**Comment by Rochet2** [comment]
What core do you use (trinity/mangos/cmangos)?
Can you give the exact error message and/or the compile output?

**Comment by matuph** [comment]
i have ElunaMangosTbc-master and eluna news

\src\game\luaengine\PlayerMethods.h(3951): error C2039: "SendMovieStart": Ist kein Element von "Player" (Quelldatei wird kompiliert ..\..\src\game\LuaEngine\LuaFunctions.cpp)
\src\game\ArenaTeam.h(29): note: Siehe Deklaration von "Player" (Quelldatei wird kompiliert ..\..\src\game\LuaEngine\LuaFunctions.cpp)

compiler is vc++ 2015


thx for support

**Comment by Rochet2** [comment]
for now use the designed commit: https://github.com/ElunaLuaEngine/Eluna/tree/e41fed0c0dd8d4acb2a1d52b2e6736e9ef89b7e0
You can switch to it by going to the LuaEngine folder and using git to check out to that - assuming you dont have any custom changes in Eluna.
`git checkout e41fed0c0dd8d4acb2a1d52b2e6736e9ef89b7e0`
Later on you can return back to master branch by doing `git checkout master`

**Comment by matuph** [comment]
ohh nice thc

**Comment by Rochet2** [comment]
The error should be fixed now. Report back if you are still having issues.
