### ISSUE TITLE
GetLootRecipient not working

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#184]
Issue: the method returns nil instead of looter possibly.
Either the code is not using the method correctly or the method is flawed.
https://github.com/Rochet2/Eluna-Lua-Scripts/commit/50f26026387b2aa46d77ef3c6d6381fdbfaa0139#commitcomment-15712732

Code: https://github.com/Rochet2/Eluna-Lua-Scripts/blob/50f26026387b2aa46d77ef3c6d6381fdbfaa0139/daily_chest_system.lua

**Comment by verawow** [comment]
TrinityCore rev. unknown 1970-01-01 00:00:00 +0000 (Archived branch) (Win32, Release)	unknown	TDB 335.59	59

It says unknown at log but I downloaded it from here
https://github.com/Quadral/335source

**Comment by Rochet2** [comment]
It seems something else is used for gameobjects to define looter than GetLootRecipient.
SetLootRecipient is used only by a few boss scripts.

**Comment by Rochet2** [comment]
With a further look it seems that mangos and TC work a bit differently regarding GetLootReprecient. GetLootReprecient doesnt really get the original looter.

As a workaround you could use this;
[code]local function onLootStateChanged(event, player, go)
    handleLoot(player, go)
    return false
end

-- Register chests
local i = 1
while CHEST[i] do
  RegisterGameObjectGossipEvent(CHEST[i], 1, onLootStateChanged)
  i = i + 1
end[/code]

instead of the existing onLootStateChanged and registers at the bottom of the script.
This uses on gossip hello hook which triggers on same event. It also returns false in the gossip hook to signal that default action should be done by code (which is to allow looting)

The method itself will not be touched as it works as core defines it, so it is a non issue.

**Comment by Rochet2** [comment]
Changing documentation a bit to reflect this.
