### ISSUE TITLE
[request] New method: ModifyPower()

### ISSUE THREAD

**Issue by zwisus** [ElunaLuaEngine/Eluna#189]
Unit 
ModifyPower()

**Comment by Rochet2** [comment]
Meanwhile use GetPower and SetPower:
`Unit:SetPower( type, Unit:GetPower( type ) + amount )`
http://eluna.emudevs.com/Unit/GetPower.html
http://eluna.emudevs.com/Unit/SetPower.html

**Comment by zwisus** [comment]
thanks

**Comment by Easelm** [comment]
You should search through the Eluna API before requesting a method. Even though you requested a valid method, the examples Rochet2 pointed out seems to argue whether or not it should be added.

**Comment by zwisus** [comment]
if maxpower < getpower + amount
setpower don't instead modifypower

eg:
amount = spell:getpowercost
if getpower + amount >= maxpower 
setpower(type,getpower+amont)=maxpower-amount

 else
it's normal,
setpower(type,getpower+amont)=modifypower(type,amount)

**Comment by zwisus** [comment]
Had ModifyMoney,why not add ModifyPower?
