### ISSUE TITLE
GlobalMethods.h  compile error

### ISSUE THREAD

**Issue by zwisus** [ElunaLuaEngine/Eluna#194]
commit:https://github.com/ElunaLuaEngine/Eluna/commit/4cd17fd9d9d1fbe8155e6268855853cd9a3415fe
compile error：
Undefined identifier：Utf8ToUpperOnlyLatin
In Mangoszero and Cmangos classic

**Comment by Rochet2** [comment]
You _should_ use the assigned version, not the latest version though.
