### ISSUE TITLE
[request] function: Add empty bot

### ISSUE THREAD

**Issue by huangwc94** [ElunaLuaEngine/Eluna#199]
Hi, I am currently working on a Lua base WOW bot system. After a long research, I still not able to implement the function that add a bot controlled player into the world. For my test, I had to open 10 or more instance of wow client in order to get a bot army.
I am wondering if Eluna can add a global function that add a no body controlled character to the world. Just login a character into the world. Like [playerbot](https://github.com/LordPsyan/LordPsyanBots) command ".add bot ". So I can make my custom AI logic and use Eluna Player Object to control it.
Thank you very much.

**Comment by Easelm** [comment]
Pretty obviously you can't implement anything since that is a third party project and it isn't implemented in Eluna. I doubt we'll implement Playerbot methods - doesn't really seem like a must-have-system since I think you are the only one who suggested something related to it.
