### ISSUE TITLE
WorldServer fails to link with "-DWITH_DYNAMIC_LINKING=1" on TrinityCore WoTLK

### ISSUE THREAD

**Issue by tanner-carter** [ElunaLuaEngine/Eluna#203]
The core fails to link worldserver executable when the C++ scripts are compiled with dynamic linking. I don't have the full output but the first line is:

`undefined reference to 'Eluna::Uninitialize()'`

**Steps to reproduce**
1. Clone WoTLK Eluna repo.
2. Update git submodule
3. Configure CMake using WITH_DYNAMIC_LINKING flag on.
4. Compile core, watch worldserver compile fail at linking step, producing error messages related to Eluna.

**Comment by Rochet2** [comment]
you ran this on linux?
Travis looks happy (build succeeded) and the settings it uses have dynamic linking set to 1
https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/blob/master/.travis.yml

**Comment by Rochet2** [comment]
Travis succeeded and my windows test succeeded.
Can you tell if you tried using the latest TC or something else that could affect this?

**Comment by tanner-carter** [comment]
Looks like it was an issue on my end. Managed to get it to build by making sure that one of the options for the scripts was changed from static to dynamic.

**Comment by Rochet2** [comment]
Can you share the failing  and possibly also the succeeding cmake configuration?
Would be nice to test and see if it really is a bug that we should fix or that should be fixed on TC.
