### ISSUE TITLE
Make RegisterEvent delay randomizable

### ISSUE THREAD

**Issue by sattelite** [ElunaLuaEngine/Eluna#205]
To easify the RegisterEvent call it would be perfect if you can call the RegisterEvent with a function as delay (or two numbers delayMin and delayMax).
This would make calls like 

```
creature:RegisterEvent(myFunction, math.random(1000, 10000), 0)
```

aktually be called in a random time between 1 and 10s instead of one time calculating the delay and then calling it in a fixed interval. Workaround so far would be

```
creature:RegisterEvent(myFunction, math.random(1000, 10000), 1)
function myFunction(..)
    dostuff()
    creature:RegisterEvent(myFunction, math.random(1000, 10000), 1)
end
```

**Comment by sattelite** [comment]
workaround so far would be

creature:RegisterEvent(myFunction, math.random(1000, 10000), 1)
function myFunction(..)
  dostuff()
  creature:RegisterEvent(myFunction, math.random(1000, 10000), 1)
end

**Comment by Rochet2** [comment]
Example
```
CreateLuaEvent(print, {1000, 10000}, 3)
17      3996    3       nil
17      5688    2       nil
17      1573    1       nil
```
