### ISSUE TITLE
Custom Spell Requirement for flying

### ISSUE THREAD

**Issue by Nupper** [ElunaLuaEngine/Eluna#206]
Changes Made
Player.cpp
Before:

bool Player::CanFlyInZone(uint32 mapid, uint32 zone) const
{
    // continent checked in SpellInfo::CheckLocation at cast and area update
    uint32 v_map = GetVirtualMapForMapAndZone(mapid, zone);
    return v_map != 571 || HasSpell(54197); // 54197 = Cold Weather Flying
}

After

bool Player::CanFlyInZone(uint32 mapid, uint32 zone) const
{
    // continent checked in SpellInfo::CheckLocation at cast and area update
    uint32 v_map = GetVirtualMapForMapAndZone(mapid, zone);
    return v_map != 571 || HasSpell(54197); // 54197 = Cold Weather Flying
    return v_map != 869 || HasSpell(93333); // 93333 = Flight Master's License
}

**Comment by Rochet2** [comment]
Hmm, doesnt look like eluna related really.
What is this about?

**Comment by Nupper** [comment]
It was a question in regards to setting up a new mapID Fly much like the Northrend functions. i do apologize...
