### ISSUE TITLE
Unable to Merge with newest TC

### ISSUE THREAD

**Issue by simple4dev** [ElunaLuaEngine/Eluna#215]
In file included from /usr/games/wow/code/src/server/game/LuaEngine/LuaFunctions.cpp:23:0:
/usr/games/wow/code/src/server/game/LuaEngine/UnitMethods.h: In function ‘int LuaUnit::DealDamage(Eluna*, lua_State*, Unit*)’:
/usr/games/wow/code/src/server/game/LuaEngine/UnitMethods.h:2577:101: error: no matching function for call to ‘Unit::CalcAbsorbResist(Unit*&, SpellSchoolMask&, DamageEffectType, uint32&, uint32*, uint32*)’
             unit->CalcAbsorbResist(target, schoolmask, SPELL_DIRECT_DAMAGE, damage, &absorb, &resist);
                                                                                                     ^
/usr/games/wow/code/src/server/game/LuaEngine/UnitMethods.h:2577:101: note: candidate is:
In file included from /usr/games/wow/code/src/server/game/Entities/Creature/Creature.h:23:0,
                 from /usr/games/wow/code/src/server/game/Globals/ObjectMgr.h:25,
                 from PrecompiledHeaders/gamePCH.h:10:
/usr/games/wow/code/src/server/game/Entities/Unit/Unit.h:2036:14: note: void Unit::CalcAbsorbResist(DamageInfo&)
         void CalcAbsorbResist(DamageInfo& damageInfo);
              ^
/usr/games/wow/code/src/server/game/Entities/Unit/Unit.h:2036:14: note:   candidate expects 1 argument, 6 provided
src/server/game/CMakeFiles/game.dir/build.make:4608: recipe for target 'src/server/game/CMakeFiles/game.dir/LuaEngine/LuaFunctions.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/LuaEngine/LuaFunctions.cpp.o] Error 1
CMakeFiles/Makefile2:1190: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Error Caused by the latest TC Changes.

**Comment by Rochet2** [comment]
https://github.com/ElunaLuaEngine/Eluna/commit/eb4eeecb6219b30b65c874191a2d74aecc9dc074
