### ISSUE TITLE
Merge Conflict

### ISSUE THREAD

**Issue by djexcitus** [ElunaLuaEngine/Eluna#216]
I use the actual Trinitycore Rev, and then i would built it with the Eluna Lua Enginge. 

When i use the following command: 

git pull --recurse-submodules https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git

then it show me the following  error:

git pull --recurse-submodules https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git
From https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
 * branch            HEAD       -> FETCH_HEAD
Auto-merging src/server/game/Handlers/CharacterHandler.cpp
Auto-merging src/server/game/Guilds/Guild.h
CONFLICT (content): Merge conflict in src/server/game/Guilds/Guild.h
Auto-merging src/server/game/Entities/Unit/Unit.cpp
Auto-merging src/server/game/Entities/Player/Player.cpp
Auto-merging src/server/game/Entities/Object/Object.cpp
Auto-merging src/server/game/Entities/GameObject/GameObject.cpp
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Rochet2** [comment]
will look on weekend (as usual).
Either use the supported TC version (which elunatrinitywotlk is on atm) or fix the conflict and maybe make a pr?

**Comment by Rochet2** [comment]
Solved in https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/4fcd7c58d0c7ce68c618e425f3acd86141ac7ab5
