### ISSUE TITLE
Eluna & TC 7.x

### ISSUE THREAD

**Issue by LuigiElleBalotta** [ElunaLuaEngine/Eluna#218]
Does Eluna works if added to TC core at patch 7.x?

**Comment by Rochet2** [comment]
Not without a lot of changes.

**Comment by LuigiElleBalotta** [comment]
Ok, this will be done? How much time will it take?

**Comment by Rochet2** [comment]
Not planned to do at the moment.
Doing it would take from weeks to months. There will likely be issues with having compatibility between the  previous patches and so on.
