### ISSUE TITLE
PLAYER_EVENT_ON_CHANNEL_CHAT 

### ISSUE THREAD

**Issue by Toshix** [ElunaLuaEngine/Eluna#22]
PLAYER_EVENT_ON_CHANNEL_CHAT = 22, / / ​​(event, player, msg, Type, lang, channel)
does not respond to the channels registered player.

**Comment by MaZyGer** [comment]
Hello maybe I have this bug but if player create new channel do event set channel to 0?

Example: You chat in a custom channel. -> print(channel) = 0
Example2: You chat in channel 2 -> print(channel) = 2

**Comment by Rochet2** [comment]
@MaZyGer Looks like your issue is not related.
Probably it is always 0. But I will not change it myself atm.
If you do some enchantment on it, do make a pull request :)
