### ISSUE TITLE
Damage taken, healing taken

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#220]
>Eluna does only have an event tied to `creature damage taken` and it doesnt have any registered events to `player take damage` or `player receive heal` 

>It would be cool to have, to make a pvpreward script based on a players dmg & healing.

**Comment by sundayz** [comment]
_OnHealthChanged_ and _OnResourceChanged_ could be implemented through _DealDamage_ and _DealHeal_ in Units and _EnvironmentalDamage_ in Players. This sounds a bit more flexible than damage taken and heal received. They can pass the old value along with the new value, and from there it can easily be determined if it is a heal or damaging effect.

I suppose this would be a performance concern if you have several hundred players on the server, given that health also regenerates close to every second.
