### ISSUE TITLE
Eluna/Lua engine for OC

### ISSUE THREAD

**Issue by CrawDance** [ElunaLuaEngine/Eluna#221]
Hey There , This is not an Issue sorry for off topic :)
 I wanna implement Eluna on Orgoncore latest rev.

There is already an OC with eluna on Bitbucket but the core seems to be outdated and buggy.

May anyone help me on this way ? Which one should I use ? Eluna for trinity ? Or eluna for Mangos ? 

any help will be appreciated.

**Comment by Rochet2** [comment]
Im not that familiar with oregoncore, so I dont know which is closer to it.
Using either is fine, but it is of course easier if its closer to oregon.

Based on the folder structure I would imagine cmangos diff to be easier to apply than TC:
https://github.com/OregonCore/OregonCore/tree/master/src/game
https://github.com/cmangos/mangos-tbc/tree/master/src/game
https://github.com/TrinityCore/TrinityCore/tree/master/src/server/game

**Comment by CrawDance** [comment]
Thanks !
Is there any other way beside GitBash to implement ? 
Adding it to the core manually I mean .
Id there is , May you help me how ?

**Comment by Rochet2** [comment]
you need to apply the diff manually if you want to do it manually.

**Comment by CrawDance** [comment]
`fatal: refusing to merge unrelated histories
`

download link of diff file would be awesome.
Regards

**Comment by Rochet2** [comment]
Try this https://github.com/ElunaLuaEngine/ElunaMangosTbc/compare/af7d750724d7bdb75ca5fa8e02ac5c462f332b0d...a5bbed301f56f7eab7b0479b4d2d84c495f57206.diff
