### ISSUE TITLE
Merge Conflicts

### ISSUE THREAD

**Issue by Asandru** [ElunaLuaEngine/Eluna#223]
Conflicts while trying to merge with trinitycore 3.3.5a branch.
Trinitycore last commit: https://github.com/TrinityCore/TrinityCore/commit/faf299459bb96355b8c5d86add3a22ae4bcd0491
**No custom modifications just fresh source**

> 
> $ git pull --recurse-submodules https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git
> From https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
>  * branch            HEAD       -> FETCH_HEAD
> Auto-merging src/server/worldserver/Main.cpp
> CONFLICT (content): Merge conflict in src/server/worldserver/Main.cpp
> Auto-merging src/server/shared/DataStores/DBCStore.h
> CONFLICT (content): Merge conflict in src/server/shared/DataStores/DBCStore.h
> Auto-merging src/server/game/World/World.cpp
> CONFLICT (content): Merge conflict in src/server/game/World/World.cpp
> Auto-merging src/server/game/Spells/SpellEffects.cpp
> CONFLICT (content): Merge conflict in src/server/game/Spells/SpellEffects.cpp
> Auto-merging src/server/game/Spells/Auras/SpellAuraEffects.cpp
> CONFLICT (content): Merge conflict in src/server/game/Spells/Auras/SpellAuraEffects.cpp
> Auto-merging src/server/game/Server/WorldSocket.cpp
> CONFLICT (content): Merge conflict in src/server/game/Server/WorldSocket.cpp
> Auto-merging src/server/game/Server/WorldSession.cpp
> CONFLICT (content): Merge conflict in src/server/game/Server/WorldSession.cpp
> Auto-merging src/server/game/Scripting/ScriptMgr.h
> Auto-merging src/server/game/Scripting/ScriptMgr.cpp
> Auto-merging src/server/game/Maps/MapManager.cpp
> Auto-merging src/server/game/Maps/Map.cpp
> CONFLICT (content): Merge conflict in src/server/game/Maps/Map.cpp
> Auto-merging src/server/game/Handlers/SpellHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/SpellHandler.cpp
> Auto-merging src/server/game/Handlers/QuestHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/QuestHandler.cpp
> Auto-merging src/server/game/Handlers/NPCHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/NPCHandler.cpp
> Auto-merging src/server/game/Handlers/MiscHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/MiscHandler.cpp
> Auto-merging src/server/game/Handlers/LootHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/LootHandler.cpp
> Auto-merging src/server/game/Handlers/ChatHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/ChatHandler.cpp
> Auto-merging src/server/game/Handlers/CharacterHandler.cpp
> CONFLICT (content): Merge conflict in src/server/game/Handlers/CharacterHandler.cpp
> Auto-merging src/server/game/Entities/Unit/Unit.cpp
> CONFLICT (content): Merge conflict in src/server/game/Entities/Unit/Unit.cpp
> Auto-merging src/server/game/Entities/Player/Player.cpp
> CONFLICT (content): Merge conflict in src/server/game/Entities/Player/Player.cpp
> Auto-merging src/server/game/Entities/Object/Object.h
> CONFLICT (content): Merge conflict in src/server/game/Entities/Object/Object.h
> Auto-merging src/server/game/Entities/Object/Object.cpp
> CONFLICT (content): Merge conflict in src/server/game/Entities/Object/Object.cpp
> Auto-merging src/server/game/Entities/GameObject/GameObject.cpp
> CONFLICT (content): Merge conflict in src/server/game/Entities/GameObject/GameObject.cpp
> Auto-merging src/server/game/Entities/Creature/Creature.cpp
> CONFLICT (content): Merge conflict in src/server/game/Entities/Creature/Creature.cpp
> Auto-merging src/server/game/Chat/Chat.cpp
> CONFLICT (content): Merge conflict in src/server/game/Chat/Chat.cpp
> Auto-merging src/server/database/Database/QueryResult.h
> Auto-merging src/server/database/Database/Field.h
> Automatic merge failed; fix conflicts and then commit the result.

**Comment by Rochet2** [comment]
Closing since merge conflicts should not happen on clean recommended install procedure.
If merging to any source on your own (including clean TC) you should be able to fix your own merge conflicts.
We/I have been updating our sources almost weekly, so wait for that instead.

For further reference read the merge and installation guides:
https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/MERGING.md
https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md
