### ISSUE TITLE
Merge Errors

### ISSUE THREAD

**Issue by Eventyret** [ElunaLuaEngine/Eluna#224]
Fresh pulled from Trinitycore first
git clone -b 3.3.5 https://github.com/TrinityCore/TrinityCore.git
Then pulled Eluna WOTLK
git pull --recurse-submodules https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git

Merge errors are as following
![image](https://user-images.githubusercontent.com/977232/27405382-3ea14950-56c9-11e7-9379-961388f1fcb8.png)

As text 
`Auto-merging src/server/worldserver/Main.cpp
CONFLICT (content): Merge conflict in src/server/worldserver/Main.cpp
Auto-merging src/server/shared/DataStores/DBCStore.h
CONFLICT (content): Merge conflict in src/server/shared/DataStores/DBCStore.h
Auto-merging src/server/game/World/World.cpp
CONFLICT (content): Merge conflict in src/server/game/World/World.cpp
Auto-merging src/server/game/Spells/SpellEffects.cpp
CONFLICT (content): Merge conflict in src/server/game/Spells/SpellEffects.cpp
Auto-merging src/server/game/Spells/Auras/SpellAuraEffects.cpp
CONFLICT (content): Merge conflict in src/server/game/Spells/Auras/SpellAuraEffe                                                                                                                  cts.cpp
Auto-merging src/server/game/Server/WorldSocket.cpp
CONFLICT (content): Merge conflict in src/server/game/Server/WorldSocket.cpp
Auto-merging src/server/game/Server/WorldSession.cpp
CONFLICT (content): Merge conflict in src/server/game/Server/WorldSession.cpp
Auto-merging src/server/game/Scripting/ScriptMgr.h
Auto-merging src/server/game/Scripting/ScriptMgr.cpp
Auto-merging src/server/game/Maps/MapManager.cpp
Auto-merging src/server/game/Maps/Map.cpp
CONFLICT (content): Merge conflict in src/server/game/Maps/Map.cpp
Auto-merging src/server/game/Handlers/SpellHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/SpellHandler.cpp
Auto-merging src/server/game/Handlers/QuestHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/QuestHandler.cpp
Auto-merging src/server/game/Handlers/NPCHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/NPCHandler.cpp
Auto-merging src/server/game/Handlers/MiscHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/MiscHandler.cpp
Auto-merging src/server/game/Handlers/LootHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/LootHandler.cpp
Auto-merging src/server/game/Handlers/ChatHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/ChatHandler.cpp
Auto-merging src/server/game/Handlers/CharacterHandler.cpp
CONFLICT (content): Merge conflict in src/server/game/Handlers/CharacterHandler.                                                                                                                  cpp
Auto-merging src/server/game/Entities/Unit/Unit.cpp
CONFLICT (content): Merge conflict in src/server/game/Entities/Unit/Unit.cpp
Auto-merging src/server/game/Entities/Player/Player.cpp
CONFLICT (content): Merge conflict in src/server/game/Entities/Player/Player.cpp
Auto-merging src/server/game/Entities/Object/Object.h
CONFLICT (content): Merge conflict in src/server/game/Entities/Object/Object.h
Auto-merging src/server/game/Entities/Object/Object.cpp
CONFLICT (content): Merge conflict in src/server/game/Entities/Object/Object.cpp
Auto-merging src/server/game/Entities/GameObject/GameObject.cpp
CONFLICT (content): Merge conflict in src/server/game/Entities/GameObject/GameOb                                                                                                                  ject.cpp
Auto-merging src/server/game/Entities/Creature/Creature.cpp
CONFLICT (content): Merge conflict in src/server/game/Entities/Creature/Creature                                                                                                                  .cpp
Auto-merging src/server/game/Chat/Chat.cpp
CONFLICT (content): Merge conflict in src/server/game/Chat/Chat.cpp
Auto-merging src/server/database/Database/QueryResult.h
Auto-merging src/server/database/Database/Field.h
Automatic merge failed; fix conflicts and then commit the result.`

**Comment by Rochet2** [comment]
https://github.com/ElunaLuaEngine/Eluna/issues/223
