### ISSUE TITLE
Implement reload message config setting

### ISSUE THREAD

**Issue by Foereaper** [ElunaLuaEngine/Eluna#227]
We should make the reload message configurable, primarily:
0 = Disabled
1 = GM announcement only
2 = Public announcement

**Comment by Rochet2** [comment]
Is there some case where this is needed?
Reload should be used only for development.

**Comment by Foereaper** [comment]
It *should* only be used for development but in some circumstances it may be needed in a production environment where taking down the entire server might not be feasible, in those cases I have received feedback that the said option was wanted

**Comment by Foereaper** [comment]
No longer relevant with the multistate implementation.
