### ISSUE TITLE
Request OnUnEquip() or HasUnEquip()

### ISSUE THREAD

**Issue by IlPicasso** [ElunaLuaEngine/Eluna#228]
Hello! I want to request a simple method to detect if player removed an item on  a slot

      if (player:HasUnEqup(18)) then
         Do all stuff, like removing an aura and send a message

**Comment by Asandru** [comment]
good idea, hope it gets aprooved and implemented

**Comment by Foereaper** [comment]
This has since been implemented as an Item Event
