### ISSUE TITLE
compilation error (linux) os_tmpname

### ISSUE THREAD

**Issue by Sheiko-bs** [ElunaLuaEngine/Eluna#229]
Hi, I have a problem with compilation. This is the first time that its happened to me.
How to fix the problem, please?

I have tried several times to start all over again.

## Error :
```
Linking CXX executable worldserver
../../../dep/lualib/liblualib.a(loslib.c.o): In function `os_tmpname':
loslib.c:(.text+0x29c): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[100%] Built target worldserver
install: missing file operand
```

## System :

> uname -a

`Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.89-2 x86_64 GNU/Linux`

**Comment by Rochet2** [comment]
The error about tmpnam is just a warning https://stackoverflow.com/a/3299943/3586583
And build succeeds with it: https://travis-ci.org/ElunaLuaEngine/ElunaTrinityWotlk/builds/268916572#L1390-L1391

The real errors are either `install: missing file operand` or something else in the log.
Please post the full compiling output, cmake output and the commands you used.

Most likely you are running the install command wrong somehow, for example you should run `make install` and you are running `install` and it produces the error for missing file operand.
