### ISSUE TITLE
JustRespawned & IsRegeneratingHealth errors

### ISSUE THREAD

**Issue by ConradBunton** [ElunaLuaEngine/Eluna#230]
### In ElunaCreatureAI.h :

if (justSpawned)
        {
            justSpawned = false;
            justSpawned ();
        }

replace by

if (justSpawned)
        {
            justSpawned = false;
            JustAppeared();
        }
--------------------------------------------------------------------------------
    // Called when creature is spawned or respawned (for reseting variables)
    void JustRespawned() override
    {
        if (!sEluna->JustRespawned(me))
            ScriptedAI::JustRespawned();
    }

replace by

    void JustAppeared() override
    {
        if (!sEluna->JustRespawned(me))
            ScriptedAI::JustAppeared();
    }

===============================================

In CreatureMethods.h :

#ifndef TRINITY
        Eluna::Push(L, creature->IsRegeneratingHealth());
#else
        Eluna::Push(L, creature->isRegeneratingHealth());
#endif
        return 1;
    }

replace by

#ifndef TRINITY
        Eluna::Push(L, creature->CanRegenerateHealth());
#else
        Eluna::Push(L, creature->CanRegenerateHealth());
#endif

**Comment by Rochet2** [comment]
Please explain what this is about.

There are no errors as seen here https://travis-ci.org/ElunaLuaEngine/ElunaTrinityWotlk/builds/270864996
If you do have errors then post them.

**Comment by ConradBunton** [comment]
I had that errors when I merged eluna with trinitycore. So I just give a possible fix, if someone has the same.

**Comment by Rochet2** [comment]
Alright
