### ISSUE TITLE
Sporadic crash on reload

### ISSUE THREAD

**Issue by Foereaper** [ElunaLuaEngine/Eluna#231]
During reload the server sporadically crashes, see screenshot below:

http://prntscr.com/gm7tq2

```
ASSERT(!i_disabledAI,
           "The disabled AI wasn't cleared!");
```

**Comment by Rochet2** [comment]
Should try after https://github.com/ElunaLuaEngine/Eluna/commit/8ecd5c62545e35b18da040a2ad84ed1ddd7792ed to see if it still exists.

**Comment by Rochet2** [comment]
Reopen if happens again .. or create new issue.
