### ISSUE TITLE
Need function to check if player is in back of the unit (Mangoszero)

### ISSUE THREAD

**Issue by Purownage** [ElunaLuaEngine/Eluna#234]
Hi all, I need help to create a function that check if player is in back of the unit. Thanks for your help ^^

**Comment by Rochet2** [comment]
Added: https://github.com/ElunaLuaEngine/Eluna/commit/fad53ae6372abac5f7f37c72fe10df43c6f5fda3
But still need to update mangos repositories with new hashes.

**Comment by Purownage** [comment]
Thanks alot! :)

**Comment by Rochet2** [comment]
mangos applied update
