### ISSUE TITLE
documentation not parsed correctly

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#235]
It seems that http://www.elunaengine.com/WorldObject/GetPlayersInRange.html
is not correct as `@param float range = 533.33333 : optionally set range. Default range is grid size`
is only showing 533 as the default range and the documentation about "optionally .." is not visible.

The documentation generator regex needs another look.

**Comment by Foereaper** [comment]
https://elunaluaengine.github.io/WorldObject/GetPlayersInRange.html

Fixed and parsed correctly now, leaving new (correct) link for posterity
