### ISSUE TITLE
request 4.3.4 merge

### ISSUE THREAD

**Issue by Asandru** [ElunaLuaEngine/Eluna#240]
Can I request a merge with TrinityCore 4.3.4 please? I tried merging and has conflicts

https://gitlab.com/trinitycore/TrinityCore_434

**Comment by ConradBunton** [comment]
The same deposit : https://github.com/TrinityCoreLegacy
I'm on it... I just have last fixes to do on CMakeLists.txt
I'll tell you if I can fix it.

**Comment by Rochet2** [comment]
We wont likely be doing it.

**Comment by ConradBunton** [comment]
I just have 3 last files left to merge without conflict:

\src\server\game\CMakeLists.txt
\src\server\scripts\CMakeLists.txt
\src\server\worldserver\CMakeLists.txt

**Comment by devilmain** [comment]
Did you have any success with merging Eluna into the 434 trinitycore. Because i can't get it to work

**Comment by ConradBunton** [comment]
Sorry, C++ isn't my speciality.

**Comment by ConradBunton** [comment]
Ok, I'll try to do it but I'll probably sometimes need some help.
If it works, it'll be merged with TrinityCoreLegacy (One of the last active deposit)
The plan is transfer commit one by one and try it each time. (Yes, it would be long)

**Comment by Asandru** [comment]
Up :+1:  I tried but so many conflicts..
