### ISSUE TITLE
On kill creature not working when in group

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#243]
Got one more bug for ya if youre interested.
ELUNA player_event_on_kill_creature 
doesnt work when in a group either.
i tried to script around the bug, but my fix only worked when not in a group as well.

by samljer at getmangos.eu
https://www.getmangos.eu/forums/topic/10389-is-drain-soul-broken/#comment-78166

**Comment by ConradBunton** [comment]
Same bug with RegisterCreatureEvent type 4 on TC WotLK.
Perhaps in creature.h or creature.cpp

**Comment by Rochet2** [comment]
Tried to reproduce the bugs on TC 3.3.5, but everything worked fine.
Player Event 7:
```
42      Player: 000001FF00CDB040        eluna RegisterPlayerEvent(7, print) // script
7       Player: 000001FF00CDB040        Creature: 000001FF0120FDC0 // without group
7       Player: 000001FF00CDB040        Creature: 000001FF011F8D40 // with group
```

Creature Event 4:
```
42      Player: 000001FF04E5ED90        eluna RegisterCreatureEvent(36, 4, print) // script
4       Creature: 000001FF051FF470      Player: 000001FF04E5ED90 // without group
4       Creature: 000001FF0450F380      Player: 000001FF04E5ED90 // with group
```

Need to test on mangos if it exists there. Does not seem to exist on TC wotlk or need better instructions for reproducing it.
