### ISSUE TITLE
Restore DepositBankMoney & WithdrawBankMoney

### ISSUE THREAD

**Issue by ConradBunton** [ElunaLuaEngine/Eluna#244]
Simply revert the commit "Remove guild bank methods"
Date : 2017.07.19 5:12pm

I dont understand why it was removed cause it worked fine.

**Comment by Rochet2** [comment]
The functions only allowed you to deposit an amount of money, but not check if it was successful or even possible.
For example there was no way to check the lower or upper bounds of the guild stash.
That is why you have no idea how much you actually put or take from the bank - could be for example that you take money from an empty bank or put money to a full bank.

**Comment by ConradBunton** [comment]
Ah ok
Can't add a DB check to fix that problem ?

**Comment by ConradBunton** [comment]
So what about Player:ModifyMoney ? There's the same problem.

**Comment by Rochet2** [comment]
The situation is a bit different since you can check how much money the player has:
http://www.elunaengine.com/Player/GetCoinage.html

**Comment by ConradBunton** [comment]
I just added a check system in my LUA script and I have no problem at all with that commands.

**Comment by ConradBunton** [comment]
Something like that...

=========== DepositBankMoney ==

Deposit = xxx		-- xxx = Money to deposit
Max_GBank = yyy	-- yyy = Maximal money in the bank

if (player:IsInGuild()) then
	Chk_Deposit = CharDBQuery("SELECT * FROM guild WHERE guildid = '"..player:GetGuildId().."';")
	if Chk_Deposit then
		Current_Bank = Chk_Deposit:GetUInt32(11)
		if Current_Bank + Deposit > Max_GBank then
			player:GetGuild():DepositBankMoney(player, (Max_GBank-Current_Bank))
		else
			player:GetGuild():DepositBankMoney(player, Deposit)
		end
	end
end

========== WithdrawBank ==

Withdraw = xxx	-- xxx = Money to Withdraw
Min_GBank = 0	-- Can use more than 0

if (player:IsInGuild()) then
	Chk_Withdraw = CharDBQuery("SELECT * FROM guild WHERE guildid = '"..player:GetGuildId().."';")
	if Chk_Withdraw then
		Current_Bank = Chk_Withdraw:GetUInt32(11)
		if (Current_Bank - Withdraw < Min_GBank) then
			player:GetGuild():WithdrawBankMoney(player, Current_Bank-Min_GBank)
		else
			player:GetGuild():WithdrawBankMoney(player, Withdraw)
		end
	end
end

**Comment by ConradBunton** [comment]
Does it help you ?
