### ISSUE TITLE
GiveXP

### ISSUE THREAD

**Issue by ConradBunton** [ElunaLuaEngine/Eluna#246]
GiveXP has a problem when you wanna add an XP bonus.
It make a loop.

**Comment by Rochet2** [comment]
This is not really a bug as giving XP should trigger giving XP hook..
However the way to avoid the loop is to not use givexp inside the event that triggers when XP is given.
Instead in the hook you can return the new XP amount.
`PLAYER_EVENT_ON_GIVE_XP                 =     12,       // (event, player, amount, victim) - Can return new XP amount`
http://www.elunaengine.com/Global/RegisterPlayerEvent.html

Example:
```lua
local function OnGiveXp(event, player, amount, victim)
    return amount * 2 -- double XP
end
RegisterPlayerEvent(12, OnGiveXp)
```

**Comment by ConradBunton** [comment]
My bad, sorry
