### ISSUE TITLE
compile error after TrinityCore@eacfa9d89

### ISSUE THREAD

**Issue by qyh214** [ElunaLuaEngine/Eluna#251]
compile error after TrinityCore/TrinityCore@eacfa9d89afcfad0cbd0715c8a84890c3ccd1c74

**Comment by ConradBunton** [comment]
Just revert "Core/AI: Kick Gossip functions upstairs, from UnitAI to CreatureAI" until the fix.

**Comment by Rochet2** [comment]
options:
1. wait for a fix
2. revert as said above and wait for fix and then revert the revert
3. fix it
We know about merge errors automatically and they will be solved as fast as we can. No need to report merge errors with TC.
