### ISSUE TITLE
PerformIngameSpawn problem

### ISSUE THREAD

**Issue by Robzyye** [ElunaLuaEngine/Eluna#253]
Hi, 
I'm starting with Eluna LUA and I can't make what I want and I don't really understand why it doesn't work.
I would like to make spawn a mob on the corps of a killed player.

`local function MobsOnCorps(event, killer, killed)`

`PerformIngameSpawn( 1, 5679, killed:GetMapId(), killed:GetInstanceId(), killed:GetX, killed:GetY, killed:GetZ, killed:GetO )`

`end`

`RegisterPlayerEvent(6, MobsOnCorps)`

Thanks

**Comment by ConradBunton** [comment]
Delete that line :

`killed:SpawnCreature( 1, 5679, killed:GetMapId(), killed:GetInstanceId(), killed:GetX, killed:GetY, killed:GetZ, killed:GetO )`

and try this :

```
local x, y, z = killed:GetRelativePoint(0, 0)
killed:SpawnCreature(5679, x, y, z, 1)
```

**Comment by Robzyye** [comment]
Thanks it's work very well !
But why does PerformIngameSpawn doesn't work ? If I need to spawn a gameobject at the Killed Position ?

```
local x, y, z = killed:GetRelativePoint(0, 0)
killed:PerformIngameSpawn( 2, 20917, killed:GetMapId(), 0, x, y, z, 1 )
```

I do like the [doc said](http://www.elunaengine.com/Global/PerformIngameSpawn.html)
2 for gobject, id, mapid, 0 for non instance, x, y, z, 1 orientation

**Comment by Robzyye** [comment]
I found a solution !

```
local x, y, z = killed:GetRelativePoint(0, 0)
killed:SummonGameObject( gobID, x, y, z, o )
```
