### ISSUE TITLE
TrinityCore 3.3.5 Interfaction don't work

### ISSUE THREAD

**Issue by gngn7** [ElunaLuaEngine/Eluna#254]
When enabling all interaction between faction, the horde can whisp the ally but the ally still speak in common

###################################################################################################
# PLAYER INTERACTION
#
#    AllowTwoSide.Interaction.Calendar
#        Description: Allow calendar invites between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Calendar = 1

#
#    AllowTwoSide.Interaction.Channel
#        Description: Allow channel chat between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Channel = 1

#
#    AllowTwoSide.Interaction.Group
#        Description: Allow group joining between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Group = 1

#
#    AllowTwoSide.Interaction.Guild
#        Description: Allow guild joining between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Guild = 1

#
#    AllowTwoSide.Interaction.Auction
#        Description: Allow auctions between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Interaction.Auction = 1

#
#    AllowTwoSide.Trade
#        Description: Allow trading between factions.
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

AllowTwoSide.Trade = 1

#
#    TalentsInspecting
#        Description: Allow/disallow inspecting other characters' talents.
#                     Doesn't affect game master accounts.
#                     2 - (Enabled for all characters)
#        Default:     1 - (Enabled for characters of the same faction)
#                     0 - (Talent inspecting is disabled)

TalentsInspecting = 2

#
###################################################################################################

**Comment by Rochet2** [comment]
You should check two side chat in RBAC in DB (auth database).
Also this is not Eluna related really. This is a TC issue / topic.
