### ISSUE TITLE
SetInCombatWithZone -> DoZoneInCombat

### ISSUE THREAD

**Issue by ConradBunton** [ElunaLuaEngine/Eluna#257]
From TC source :
Ariel's hash commit 7c9722a4ae08b5f283f6a085a411e37604a7da9f (22/01/2018 19H00)
That change makes error in CreatureMethods.h (1013 & 1015) and LuaFunctions.cpp (801)

**Comment by Rochet2** [comment]
Please stop posting these issues every week.

https://github.com/ElunaLuaEngine/Eluna/issues/241#issuecomment-342948342
> We get email notifications of these.
Also if you merge to cores then you should fix the merge errors on your own.
