### ISSUE TITLE
request cmangos classic repo update

### ISSUE THREAD

**Issue by cavaclub** [ElunaLuaEngine/Eluna#258]
if you could update the integrated cmangos classic repository yours, i appreciate.
I dont know if i need to open another issue, but, to do not open,

How do i compile extractors? for cmangos of course 
can i know if i need to git clone the cmangos classic repository?
you guys say : then continue compiling using cmangos instructions but you dont say if i need to do all cmangos instructions process.... please???!

**Comment by Rochet2** [comment]
I personally will not do this at this time.

I actually was going to do it over the holidays, but the task was a bit more difficult than expected.
Also some things required core edits that I would rather have as a part of the core than Eluna code, like https://github.com/cmangos/mangos-wotlk/pull/255

**Comment by Rochet2** [comment]
https://github.com/ElunaLuaEngine/Eluna/issues/245
