### ISSUE TITLE
[cmangos-classic] Hunter trap doesnt appear at all but still trigger.

### ISSUE THREAD

**Issue by Purownage** [ElunaLuaEngine/Eluna#260]
Hello, I've noticed that Hunter Trap on latest core doenst work well.
First of all the trap didnt appear on the floor, but if a mobs approach its still trigger but in a way too large radius like 10 yards. Normaly you have to step on it to make it trigger! tyvm ^^

**Comment by Rochet2** [comment]
You should try on latest cmangos-classic from cmangos repositories: https://github.com/cmangos/mangos-classic
If the bug happens there then report it to their issue tracker: https://github.com/cmangos/issues/issues
If the bug does not happen with latest cmangos-classic then need to wait until Eluna is updated for latest cmangos or update it yourself. Currently cmangos is not being actively updated.
