### ISSUE TITLE
Reload eluna message

### ISSUE THREAD

**Issue by Dalaspring** [ElunaLuaEngine/Eluna#261]
Is it possible to make reload eluna only shown to GMs? Similar to the other reload commands in-game?
Even though reloading is meant for test servers I think it would be great to hide it to normal players incase you need to hotfix a script but many players are online.

**Comment by Dalaspring** [comment]
I'm sorry.  i saw it was already requested https://github.com/ElunaLuaEngine/Eluna/issues/227

**Comment by Foereaper** [comment]
Closing as duplicate
