### ISSUE TITLE
Why does GetGameObjectAI use OnSpawn?

### ISSUE THREAD

**Issue by AyaseCore** [ElunaLuaEngine/Eluna#268]
I have a question.Why does GetGameObjectAI use OnSpawn?

src\server\game\Scripting\ScriptMgr.cpp
```
GameObjectAI* ScriptMgr::GetGameObjectAI(GameObject* gameobject)
{
    ASSERT(gameobject);
#ifdef ELUNA
    sEluna->OnSpawn(gameobject);
#endif
    GET_SCRIPT_RET(GameObjectScript, gameobject->GetScriptId(), tmpscript, nullptr);
    return tmpscript->GetAI(gameobject);
}
```

**Comment by Rochet2** [comment]
GetGameObjectAI should occur when an object is spawned / appears in world.
What do you think is a more appropriate place?
There is no real "on spawn" c++ hook, so maybe it should be removed altogether.
For creatures there is JustAppeared c++ hook.

**Comment by AyaseCore** [comment]
Thank you for your reply. @Rochet2
