### ISSUE TITLE
[Request] Add 'SendWorldText'

### ISSUE THREAD

**Issue by TiTaKaZ** [ElunaLuaEngine/Eluna#276]
add 'SendWorldText' method, which uses strings from 'trinity_string' and parameters. Just like in C++

**Comment by Asandru** [comment]
And what if we want to use our own text? Do we have to add that text in database? 
I go for a NO here, unless you make the parameters optional.

**Comment by TiTaKaZ** [comment]
I hope you know that there's a SendWorldMessage thingy ;) You are unfamiliar with Eluna Engine...
