### ISSUE TITLE
Eluna Lua Engine install error

### ISSUE THREAD

**Issue by hahalmtdhl** [ElunaLuaEngine/Eluna#284]
#Operation:
1、`git clone https://github.com/cmangos/mangos-tbc.git`
2、In parent directory git bash:
`$ git submodule add https://github.com/ElunaLuaEngine/ElunaMangosTbc.git   Lua`
3、In parent directory git bash:
`$ git submodule update --init --recursive`

The problem is that I haven't found any changes in the parent directory, no LUA_SCRIPT after cmake and compilation, and no LUA-related settings in the configuration file. I've tried a lot of ways (including installation guides). Who can help me?

**Comment by hahalmtdhl** [comment]
@Rochet2 希望你能看到。感谢！

**Comment by Rochet2** [comment]
You are not following the installation guide.
https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md

Latest cmangos is not supported.

**Comment by hahalmtdhl** [comment]
If you do not support the latest cmangos, do you know where there is CMANGOS that has integrated the LUA module?
@Rochet2
