### ISSUE TITLE
[Question] How can I use C functions in the core to call in lua script?

### ISSUE THREAD

**Issue by Veraciel** [ElunaLuaEngine/Eluna#292]
This is my code that using a C++ function calling a DBtable reloaded in Lua.
I'm a noob for scripts and c++ but I tried to search and read for several days and did what i can do with my best. I need your wise answers  

in Main.cpp 

I included lua headers.

#include "LootMgr.h"
extern "C" {
#include "lua.h"
#include "luaLib.h"
#include "lauxlib.h"
#include "lua.hpp"
};

/*define a function to call "LoadLootTemplates_Gameobject() in LootMgr.cpp" */

static int reloadgbtable(lua_State* L)
{
    LoadLootTemplates_Gameobject();       /* a function to reload gameobject_loot_template */
    return 1;
}

/// Launch the Trinity server
extern int main(int argc, char** argv)
{
    lua_State* L = luaL_newstate();

    luaL_openlibs(L);

    /* register our function */
    lua_pushcfunction(L, reloadgbtable);
    lua_register(L, "reloadgbtable", reloadgbtable);

    /* run the script */
    luaL_dofile(L, "Server.lua");
    /* cleanup Lua */
    lua_close(L);
 
.
.

in Server.lua (lua-scripts/test/Server.lua)

reloadgbtable()

then I get the msg "attempt to call global 'reloadgbtable' (a nil value)everytime" when I call the function in lua.

How can I use those kind of C++ functions which is not defined in Eluna API?

I may missed sth basic things or made a stupid mistakes because of lack of knowledge.

Sorry for my bad English. but I really need your help to fix and get answer.
Thanks.

but I always get  the msg like "attempt to call global 'reloadgbtable' (a nil value)"

**Comment by Rochet2** [comment]
Your code seems like you are trying to make a whole new lua instance and call your script without actually using Eluna in any way. That means that you will not be able to call the function from Eluna.
Did you mean to add the function to Eluna?

If you just wanted to add LoadLootTemplates_Gameobject as a function to Eluna, you would do it like this:
```diff
diff --git a/GlobalMethods.h b/GlobalMethods.h
index 39cc6f0..37bcfdf 100644
--- a/GlobalMethods.h
+++ b/GlobalMethods.h
@@ -8,6 +8,7 @@
 #define GLOBALMETHODS_H

 #include "BindingMap.h"
+#include "LootMgr.h"

 #ifdef AZEROTHCORE
 #include "BanManager.h"
@@ -3144,5 +3145,14 @@ namespace LuaGlobalFunctions

         return 0;
     }
+
+    /**
+     * Reloads GameObject loot templates.
+     */
+    int reloadgbtable(lua_State* L)
+    {
+        LoadLootTemplates_Gameobject();
+        return 0;
+    }
 }
 #endif
diff --git a/LuaFunctions.cpp b/LuaFunctions.cpp
index 643af39..a691e85 100644
--- a/LuaFunctions.cpp
+++ b/LuaFunctions.cpp
@@ -143,6 +143,7 @@ luaL_Reg GlobalMethods[] =
     { "CreateUint64", &LuaGlobalFunctions::CreateULongLong },
     { "StartGameEvent", &LuaGlobalFunctions::StartGameEvent },
     { "StopGameEvent", &LuaGlobalFunctions::StopGameEvent },
+    { "reloadgbtable", &LuaGlobalFunctions::reloadgbtable },

     { NULL, NULL }
 };
```

You can then call it in any lua script that you run through Eluna by calling `reloadgbtable()`.
In practice that would mean that you need to place your lua script file to `lua_scripts` folder in your server folder.

**Comment by Veraciel** [comment]
Oh Thank you so much Rochet2 for rapid and sincere reply. Im kinda a big fan of your scripts and very inspired with what you contributed. I will try your code ASAP. Thanks!!

**Comment by Veraciel** [comment]
> Oh Thank you so much Rochet2 for rapid and sincere reply. Im kinda a big fan of your scripts and very inspired with what you contributed. I will try your code ASAP. Thanks!!

This is perfectly working ! Thank you so much !

**Comment by Rochet2** [comment]
np
