### ISSUE TITLE
Global::Ban doesn't work properly on AC 3.3.5a

### ISSUE THREAD

**Issue by redrocket94** [ElunaLuaEngine/Eluna#293]
On using BanMode 0 nothing happens, BanMode 1 nothing happens, but when using BanMode 2 the account is banned.
None of the numbers up to 40 except for 2 does anything.

**Comment by Rochet2** [comment]
Can you try the same with .ban command?
Can you provide examples of what fails and succeeds?
Banning may not mean that the character is instantly kicked from server, so make sure you try to relog when testing.

By inspecting the code it seems to function like .ban command. So if ban command works then need to figure out what is different.

**Comment by redrocket94** [comment]
.ban works fine for both account, character and IP, all are disconnected and unable to login on success

Ban(1, player:GetName(), 10, player:GetName()) -- does nothing (tried relog)
Ban(2, player:GetName(), 10, player:GetName()) -- kicks & bans me from the server
Ban(3, player:GetName(), 10, player:GetName()) -- does nothing (tried relog)

.ban character/account/ip all work

Code I used to test:
`function banSelf(event, player, command)
    	if command == "banme" then
    		Ban(2, player:GetName(), 10, player:GetName())
    	end
    end

    RegisterPlayerEvent(42, banSelf)`

**Comment by Rochet2** [comment]
Alright. I think the documentation is just not clear on what is being banned exactly.
It is probable that the nameOrIP should be the character name or account name or ip depending on the method of banning, so character name cannot be used for account or IP. Also there is no error when the account or player etc is not found or a way to check if the user was really banned.

So should improve doc and maybe return a status of what happened with the ban (success, player not found, error/wrong syntax).

**Comment by redrocket94** [comment]
Very well, Ban() with enum 1 (Account) works now when I pass GetAccountName(), but Ban() with 2 (character, GetName()) still does not work. When PlayerName is passed into it it bans the account instead of the character.

**Comment by Rochet2** [comment]
Fixed Ban() documentation.
Fixed banning of character to ban character instead of account.
Added a return value to Ban()
Added some errors if invalid arguments given to Ban()

See https://github.com/ElunaLuaEngine/Eluna/commit/34151cc7449f8d8764bd06c10c9e26a64c9edbe7
