### ISSUE TITLE
Merging Eluna conflict

### ISSUE THREAD

**Issue by opiums9** [ElunaLuaEngine/Eluna#295]
Hi, I can not perform Merging Eluna, how can I be?

```
root@debian:~# git clone https://github.com/TrinityCore/TrinityCore.git -b3.3.5
Клонирование в «TrinityCore»…
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 503196 (delta 7), reused 8 (delta 5), pack-reused 503173
Получение объектов: 100% (503196/503196), 711.51 MiB | 732.00 KiB/s, готово.
Определение изменений: 100% (362839/362839), готово.
Распаковка файлов: 100% (12492/12492), готово.
root@debian:~# cd TrinityCore
root@debian:~/TrinityCore# git pull --recurse-submodules https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git
remote: Enumerating objects: 9897, done.
remote: Counting objects: 100% (9188/9188), done.
remote: Compressing objects: 100% (3168/3168), done.
remote: Total 8927 (delta 6689), reused 7785 (delta 5757), pack-reused 0
Получение объектов: 100% (8927/8927), 3.55 MiB | 621.00 KiB/s, готово.
Определение изменений: 100% (6689/6689), завершено с 84 локальными объектами.
Из https://github.com/ElunaLuaEngine/ElunaTrinityWotlk
 * branch                  HEAD       -> FETCH_HEAD
Автослияние src/server/game/Spells/SpellEffects.cpp
Автослияние src/server/game/Spells/Auras/SpellAuraEffects.cpp
Автослияние src/server/game/Server/WorldSession.cpp
Автослияние src/server/game/Handlers/SpellHandler.cpp
Автослияние src/server/game/Handlers/QuestHandler.cpp
КОНФЛИКТ (содержимое): Конфликт слияния в src/server/game/Handlers/QuestHandler.cpp
Автослияние src/server/game/Handlers/NPCHandler.cpp
Автослияние src/server/game/Handlers/LootHandler.cpp
Автослияние src/server/game/Handlers/ChatHandler.cpp
Автослияние src/server/game/Handlers/CharacterHandler.cpp
Автослияние src/server/game/Entities/Unit/Unit.cpp
Автослияние src/server/game/Entities/Player/Player.cpp
Автослияние src/server/game/Entities/Object/Object.h
Автослияние src/server/game/Entities/Object/Object.cpp
Автослияние src/server/game/Entities/GameObject/GameObject.cpp
Автослияние src/server/game/Entities/Creature/Creature.cpp
Автослияние src/server/game/Combat/CombatManager.cpp
Не удалось провести автоматическое слияние; исправьте конфликты и сделайте коммит результата.
```

**Comment by Rochet2** [comment]
Eluna is not yet merged to latest TC that had breaking changes.
You must either use older TC version or wait for us to fix the merge or fix the merge yourself (and maybe make a PR to us about the fix).

**Comment by Rochet2** [comment]
Now merged with latest TC and merging should work unless you have custom changes that prevent merging with latest TC.

**Comment by opiums9** [comment]
Well thank you! now and merging works and clone, but unfortunately when compiling, an error occurs :(
```
[ 24%] Building CXX object src/server/game/CMakeFiles/game.dir/Calendar/CalendarMgr.cpp.o
[ 24%] Building CXX object src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
/root/ElunaTrinityWotlk/src/server/game/Chat/Chat.cpp:35:10: fatal error:
      'LuaEngine.h' file not found
#include "LuaEngine.h"
         ^
1 error generated.
src/server/game/CMakeFiles/game.dir/build.make:1302: ошибка выполнения рецепта для цели «src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o»
make[2]: *** [src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o] Ошибка 1
CMakeFiles/Makefile2:1341: ошибка выполнения рецепта для цели «src/server/game/CMakeFiles/game.dir/all»
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
```

**Comment by Rochet2** [comment]
Are you sure LuaEngine.h exists?
Did you run cmake again?
I tried a full recompile without PCH on windows and all went fine.

**Comment by opiums9** [comment]
I tried to compile 2 times and without success. The LuaEngine.h file in the Chat folder does not exist.
```
root@debian:~/ElunaTrinityWotlk/src/server/game/Chat# cd /root/ElunaTrinityWotlk/src/server/game/Chat/
root@debian:~/ElunaTrinityWotlk/src/server/game/Chat# ls -l
итого 92
drwxr-xr-x 2 root root  4096 июл  6 09:51 Channels
drwxr-xr-x 2 root root  4096 июл  6 09:51 ChatCommands
-rw-r--r-- 1 root root 39503 июл  6 09:51 Chat.cpp
-rw-r--r-- 1 root root  8628 июл  6 09:51 Chat.h
-rw-r--r-- 1 root root 13331 июл  6 09:51 Hyperlinks.cpp
-rw-r--r-- 1 root root  7739 июл  6 09:51 Hyperlinks.h
-rw-r--r-- 1 root root  5477 июл  6 09:51 HyperlinkTags.cpp
```
Today I downloaded everything again and tried again, my actions:
```
git clone https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git
cd ~/ElunaTrinityWotlk/
git remote add rochet2 https://github.com/Rochet2/TrinityCore.git
git pull rochet2 multivendor_3.3.5
git pull rochet2 dressnpcs_3.3.5
mkdir build
cd build
cmake ../ -DCMAKE_BUILD_TYPE=Debug
make
```
And I got the same error:
```
[ 24%] Building CXX object src/server/game/CMakeFiles/game.dir/Chat/Chat.cpp.o
/root/ElunaTrinityWotlk/src/server/game/Chat/Chat.cpp:35:10: fatal error:
      'LuaEngine.h' file not found
#include "LuaEngine.h"
         ^
1 error generated.
```

**Comment by Rochet2** [comment]
LuaEngine.h is supposed to exist inside LuaEngine folder.
From the actions you posted it seems you forgot to get the submodule.
Check out step 4 of https://github.com/ElunaLuaEngine/Eluna/blob/master/docs/INSTALL.md#installation

**Comment by opiums9** [comment]
Made such actions:
```
root@debian:~# git clone https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git
Клонирование в «ElunaTrinityWotlk»…
remote: Enumerating objects: 4992, done.
remote: Counting objects: 100% (4992/4992), done.
remote: Compressing objects: 100% (2007/2007), done.
remote: Total 384638 (delta 3332), reused 4044 (delta 2710), pack-reused 379646
Получение объектов: 100% (384638/384638), 184.39 MiB | 2.58 MiB/s, готово.
Определение изменений: 100% (299270/299270), готово.
Распаковка файлов: 100% (12556/12556), готово.
root@debian:~# cd ElunaTrinityWotlk/
root@debian:~/ElunaTrinityWotlk# git submodule init
Подмодуль «src/LuaEngine» (https://github.com/ElunaLuaEngine/Eluna.git) зарегист                                                                                        рирован по пути «src/server/game/LuaEngine»
root@debian:~/ElunaTrinityWotlk# git submodule update
Клонирование в «/root/ElunaTrinityWotlk/src/server/game/LuaEngine»…
Подмодуль по пути «src/server/game/LuaEngine»: забрано состояние «7e41c418bcbfc1                                                                                        0677ee8cef8821e750d894d339»
root@debian:~/ElunaTrinityWotlk# cd /root/ElunaTrinityWotlk/src/server/game/Chat/
root@debian:~/ElunaTrinityWotlk/src/server/game/Chat# ls -l
итого 92
drwxr-xr-x 2 root root  4096 июл  6 11:57 Channels
drwxr-xr-x 2 root root  4096 июл  6 11:57 ChatCommands
-rw-r--r-- 1 root root 39503 июл  6 11:57 Chat.cpp
-rw-r--r-- 1 root root  8628 июл  6 11:57 Chat.h
-rw-r--r-- 1 root root 13331 июл  6 11:57 Hyperlinks.cpp
-rw-r--r-- 1 root root  7739 июл  6 11:57 Hyperlinks.h
-rw-r--r-- 1 root root  5477 июл  6 11:57 HyperlinkTags.cpp
root@debian:~/ElunaTrinityWotlk/src/server/game/Chat#
```
But the LuaEngine.h file is still not there, it is also not in the repository itself:
https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/tree/master/src/server/game/Chat

**Comment by Rochet2** [comment]
The file should be at `src/server/game/LuaEngine/LuaEngine.h`. Is it there?
What does this say?
```
Клонирование в «/root/ElunaTrinityWotlk/src/server/game/LuaEngine»…
Подмодуль по пути «src/server/game/LuaEngine»: забрано состояние «7e41c418bcbfc10677ee8cef8821e750d894d339»
```

**Comment by opiums9** [comment]
Yes, the file is there.
I think it says where the submodule is cloned and which commit it accepts.
P.S. I use Debian 9.

**Comment by Rochet2** [comment]
You ran cmake right before building?
Did you try delete the build folder / change it so that there is a new one without previous cache?

**Comment by opiums9** [comment]
Before each attempt, I completely deleted the ElunaTrinityWotlk folder, and then cloned and re-compiled
`rm -rf ~/ElunaTrinityWotlk`

**Comment by Rochet2** [comment]
I can only try this on monday as I dont have a machine where I can install debian on atm.

> Why files from this folder are not transferred to the destination?

Not sure what you mean. Where should they be transferred to? What destination?

**Comment by opiums9** [comment]
An error occurs during compilation, it says that the file 'LuaEngine.h' was not found in '/root/ElunaTrinityWotlk/src/server/game/Chat/'. With the git submodule init and git submodule update commands, the file should get there, like all the others, at their destination. But this does not happen and the file remains at the address 'src/server/game/LuaEngine'. I think that 'LuaEngine.h' should be in '/root/ElunaTrinityWotlk/src/server/game/Chat/LuaEngine.h', right?

**Comment by Rochet2** [comment]
No. Cmake handles the include paths in such a way that any file inside 'game' can be included to any other file in 'game' folder. LuaEngine.h is used from a lot of places, not just the Chat folder.
Compare it to how Player.h is everywhere, but it certainly is not inside every folder.

**Comment by opiums9** [comment]
I was finally able to compile and install the application!
I post the complete action log: https://gist.github.com/opiums9/f66358926d84fe34b7df0a5f4f9d5b98

I do not understand why it did not work right away. Thank you so much for your help!

**Comment by opiums9** [comment]
Hi, is it really that bad with the version of ElunaTrinityWotlk
Link: https://gist.github.com/opiums9/7e451bada339d5499d6700e0cbed002a
And your link: https://travis-ci.org/ElunaLuaEngine/ElunaTrinityWotlk

**Comment by Rochet2** [comment]
I will update once I have time. I do get automatic email notifications when TC no longer merges with Eluna. TC and eluna merge gets broken almost weekly since TC changes their function names and such a lot. There is no need to notify me via ticket every time.
Merging with any core is not supported for exactly for the reason that people keep getting broken merges that they will not fix themselves.

The recommended way to use Eluna is to use ElunaLuaEngine/ElunaTrinityWotlk repository directly and not to merge with TC.
You will then likely have problems with merging other sources though. In those usually the recommended way is to use a diff and not merge to avoid getting all of the TC history.

You can also try find suitable commits that do merge together and use for example this method: https://stackoverflow.com/questions/8223103/merge-up-to-a-specific-commit so you can merge a bit older versions together and avoid the merge conflicts with the latest code.
