### ISSUE TITLE
[Question] Which Lua compiler does Eluna use?

### ISSUE THREAD

**Issue by FiftyTifty** [ElunaLuaEngine/Eluna#296]
Lua has woeful performance in most benchmarks, but according to (https://github.com/r-lyeh-archived/scriptorium) LuaJIT is 12x faster than plain LUA. Which one does Eluna use?

**Comment by Rochet2** [comment]
Eluna uses Lua 5.2.
It may be possible that you can choose your lua version in the future (jit or lua 5.1 probably).

In any case,
even if the benchmark site shows some native tests written, the actual run.bat only seems to test fib.lua which uses no C calls. The benchmarks usually use plain lua code, which luajit can optimise close to C code performance. Eluna however has a lot of C -> lua -> C function calls which are probably a lot slower. The 12x speed is likely not what you would experience overall. You would get that only for the plain lua code and other parts might be slightly faster. It would be best to benchmark a situation closer to what Eluna has.

In addition to lua version it would be beneficial for speed to design the architecture to allow more parallelism. Currently all access to lua is guarded by a mutex.

**Comment by MajinCry** [comment]
LuaJIT appears to have the best performance. Bog standard Lua is woefully bad, and I don't really see any use for it; if the scripting language has to be one of the high level languages, C# has decent enough performance, unlike Lua, Ruby, Python, Perl, and Java. Pascal Script would also be a good choice.

Eluna doesn't support parallel scripting? That's extremely limiting; single thread and poor performance makes it unusable for anything significant.

**Comment by Foereaper** [comment]
On the single threaded performance, this is something we have discussed rewriting, but due to lack of development resources this is not something we'll probably get around to any time soon. 

Rochet is primarily the only one maintaining the project at the moment, and interest from other developers have yet to surface. 

If someone is interested in rewriting the current code to include either other compilers or multithreading support, we'd be more than willing to help out where need be.

**Comment by Rochet2** [comment]
From https://github.com/azerothcore/mod-eluna-lua-engine/issues/22#issuecomment-583090473

> For ppl interested, there is a somewhat working version at
> https://github.com/ElunaLuaEngine/Eluna/tree/luajit (eluna)
> https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/tree/luajit (TC)
> luajit branch which you can see the changes of.
> Basically there are some minor changes in eluna and core and complete replacement of deps/lualib.
> 
> The branch implements the possibility of choosing your lua version (5.2, 5.1, luajit).
> The jit build probably does not work on mac.
> Note that the language itself has changes in jit vs 5.2, so some scripts may not work without changes.
> 
> This however does not mean that I am going to work on getting jit supported any time soon.
Any help is appreciated. I decided to make this as a starting point for future work as I had most of the things already done for another project.

**Comment by ciber96** [comment]
Sorry to bump the topic, but does Eluna support compiled Lua scripts and is there any performance gain?

**Comment by Foereaper** [comment]
Yes it supports precompiled scripts, not it does not improve performance. Precompiled scripts, as well as normal scripts, have to be converted to byte code before execution, so there's no performance gain what so ever. Precompiled scripts load a bit faster, but this is done once on startup so you wouldn't really benefit from it.

**Comment by Rochet2** [comment]
@ciber96 We assume you meant using of for example [luac](https://www.lua.org/manual/5.2/luac.html) to compile your lua script. Do tell if that is not what you meant.
