### ISSUE TITLE
[Bug] GetAITarget creature method is broken in Trinity

### ISSUE THREAD

**Issue by stoneharry** [ElunaLuaEngine/Eluna#311]
The current implementation for GetAITarget Creature method calls:

`auto const& threatlist = creature->GetThreatManager().GetThreatenedByMeList();`

This should instead be:

`auto const& threatlist = creature->GetThreatManager().GetSortedThreatList();`

I would submit a pull request but the fix I've made is pretty hardcoded for Trinity.

**Comment by Rochet2** [comment]
@Foereaper

**Comment by Foereaper** [comment]
Pushed a quick fix for this, super ugly, really needs to be cleaned up.
