### ISSUE TITLE
player:LearnTalent doesn't work in 3.3.5a

### ISSUE THREAD

**Issue by ogroe** [ElunaLuaEngine/Eluna#315]
Player:LearnTalent( talent_id, talentRank ) doesn't work. When calling the function, no error message is shown, nor is any talent learned.

**Comment by Sequininha** [comment]
I can't use Player:LearnTalent( talent_id, talentRank ) Can anyone do it for LUA? I've seen on some wow server that it's possible for you to click on an npc and he'll give you the build. Anybody know?

**Comment by Rochet2** [comment]
The function works at least on TrinityCore.
The function takes in a talent ID and a talent rank. These come from the talent DBC file.
They are not spell IDs or numbers of the talents in the tree.

So likely you are using the wrong IDs or you are using the function on some other core where it may actually be faulty.
You can test it by making a priest, level them to at least 10 using `.level 10` and then calling `player:LearnTalent(342, 0)` which learns the unbreakable will talent's first rank.

Note that this spends talent points, so the player must have free talent points to do this.
