### ISSUE TITLE
Suggestion, eluna .reload specific script

### ISSUE THREAD

**Issue by CyberMist2** [ElunaLuaEngine/Eluna#318]
I would like to suggest changing the **.reload eluna** command to a specific target file name.

Why? Because while running some scripts, if you reload the eluna scripts, those scripts are interrupted, for example phased boss scripts, or in progress timed events.

**Comment by xIvan0ff** [comment]
You can code that yourself, inside that file. I believe so.

**Comment by Foereaper** [comment]
This is probably not going to be implemented. When you load a script, its content gets read into the state. We don't keep track of what exactly is loaded into the state for each individual script in a way that allows us to "unload" what has already been loaded.

As an example, if your script has two functions, and we load both these functions, they now exist in the state. If you were to remove a function and reload the script, one function would be overwritten by the new one, but the old removed function would still exist.
