### ISSUE TITLE
Confused users report issues at TC repo

### ISSUE THREAD

**Issue by jackpoz** [ElunaLuaEngine/Eluna#320]
Some confused users report Eluna issues to TC repo at https://github.com/TrinityCore/TrinityCore/issues instead of reporting them here at https://github.com/ElunaLuaEngine/Eluna/issues .
See https://github.com/TrinityCore/TrinityCore/issues/24851 as example.

It would help to update the README.md links .

**Comment by lordSeaworth** [comment]
This was totally my fault. Didn't even thought about that it is a fork so the README.md points to the official repository. Was so wrapped up in trying to find where to post. I apologize for the inconvenience I caused.

**Comment by xIvan0ff** [comment]
I experience the same issue, any idea?

**Comment by Foereaper** [comment]
I'll take a look at updating the readme links at some point, we kinda left it as is since it was a fork, but I can see where the confusion arises.
