### ISSUE TITLE
CREATURE_EVENT_ON_DAMAGE_TAKEN does not seem to update the damage returned

### ISSUE THREAD

**Issue by tikki100** [ElunaLuaEngine/Eluna#333]
```lua
local function Test_AI(event, pUnit, target, dmg)
    if (event == 9) then
        pUnit:SendUnitSay("Recieved a total of "..dmg, 0)
        if (pUnit:GetHealth() - dmg < 1) then
            pUnit:RemoveEvents()
            dmg = 0
            pUnit:SendUnitSay("Returning new "..dmg, 0)
            return 0
        end
    end
end

RegisterCreatureEvent(TestAI_ID, 9, Test_AI)
```

This does not work. The damage does not get updated.

When troubleshooting, I found that in the `DamageTaken`function in the `CreatureHooks.cpp` file, the loop never enters the part where the damage is updated to the new value. Unfortunately, I can not understand exactly what is going on in the loop :)

**Comment by Rochet2** [comment]
The documentation seems to be a bit lacking.
The function can return true or false to indicate if the entire event should be cancelled and a number to be used as damage.

https://github.com/ElunaLuaEngine/Eluna/blob/5a29f0a9ea79eb8b91b196fc1a1904de2762b08c/CreatureHooks.cpp#L124-L139
In the loop each function registered for the event is called.
Each time the first return value is checked and if it is a truthy boolean value, then in the AI script no default damage handling is triggered. https://github.com/ElunaLuaEngine/Eluna/blob/5a29f0a9ea79eb8b91b196fc1a1904de2762b08c/ElunaCreatureAI.h#L98-L105
The second return value is then checked for a number value and stored to the damage variable as well as the call arguments for other registered events.

In practice, the fix in the code is to use `return false, 0` and fix in the documentation is to document the two return values.

**Comment by tikki100** [comment]
> 
> 
> The documentation seems to be a bit lacking.
> The function can return true or false to indicate if the entire event should be cancelled and a number to be used as damage.
> 
> https://github.com/ElunaLuaEngine/Eluna/blob/5a29f0a9ea79eb8b91b196fc1a1904de2762b08c/CreatureHooks.cpp#L124-L139
> 
> In the loop each function registered for the event is called.
> Each time the first return value is checked and if it is a truthy boolean value, then in the AI script no default damage handling is triggered.
> 
> https://github.com/ElunaLuaEngine/Eluna/blob/5a29f0a9ea79eb8b91b196fc1a1904de2762b08c/ElunaCreatureAI.h#L98-L105
> 
> The second return value is then checked for a number value and stored to the damage variable as well as the call arguments for other registered events.
> 
> In practice, the fix in the code is to use `return false, 0` and fix in the documentation is to document the two return values.

Thank you for your quick thorough answer Rochet. I can confirm that `return false, 0` indeed works as intended. Shall I leave the issue open, as a reminder for updating the documentation? :D
