### ISSUE TITLE
[NEED HELP] How to register an event which player finish some quest

### ISSUE THREAD

**Issue by CalsRanna** [ElunaLuaEngine/Eluna#334]
I try to find some docs from api, but i didn't get any useful event. How can i do this?

**Comment by Rochet2** [comment]
http://elunaluaengine.github.io/Global/RegisterCreatureEvent.html
Use the quest reward event here.

**Comment by CalsRanna** [comment]
I didn't mean one or some sepcified quest, how to register an event to each quest?
