### ISSUE TITLE
Multiple locales support

### ISSUE THREAD

**Issue by jfastnacht** [ElunaLuaEngine/Eluna#344]
Is there any plan for Eluna to support multiple locales? Right now functions like `Unit:SendUnitYell` just sends the same message to everyone regardless of the client locale AFAIK.

Any arguments against reusing `creature_ai_texts` which supports locales already? Or creating a similar table for Eluna locales? Or handle them within the lua_scripts folder as seperate locale files and use the locale aware methods within the specific cores for creature chat.

**Comment by Foereaper** [comment]
Though this is a bit of a late answer, you can write your own string handling for locales using GetDbcLocale. There's no plan to implement locale support on the method wrapper level.
