### ISSUE TITLE
[Feature request] Global:SendMail should return the GUIDs of the created items

### ISSUE THREAD

**Issue by 55Honey** [ElunaLuaEngine/Eluna#346]
Currently Global:SendMail returns nothing.

If it returned the GUIDs of the new items it created by sending a mail, these items could be easily altered e.g. by adding enchants/gems or making them soulbound.
As of now, without the returned GUIDs, one would need to query the db before and after sending the mail and compare the recipients whole mail.

If that's possible i suggest to let the method return an array containing the GUIDs.

https://github.com/ElunaLuaEngine/Eluna/blob/6d7ab9c35efa323d9b432276e7f71b277ce7d139/GlobalMethods.h#L2070
I think thats the spot.

**Comment by Rochet2** [comment]
Merged
