### ISSUE TITLE
Wrong packet event?

### ISSUE THREAD

**Issue by TechInterMezzo** [ElunaLuaEngine/Eluna#350]
https://github.com/ElunaLuaEngine/Eluna/blob/8f5c4699b2531c408b615f55270541a7267c742b/PacketHooks.cpp#L119

I didn't try this engine yet but when I looked over the code I found that line above in a receive function. That looks wrong.

**Comment by Rochet2** [comment]
Fixed in https://github.com/ElunaLuaEngine/Eluna/commit/cfe356cf5b02c52a5fef06b0474f2e22796b2e9e
