### ISSUE TITLE
upgrade to latest tc

### ISSUE THREAD

**Issue by qyh214** [ElunaLuaEngine/Eluna#363]
can you have the time upgrade to https://github.com/TrinityCore/TrinityCore/commit/302c60d3dd8e2734b32d239142c72b1add22aad9

and other a lot of repo latest update was more than a month ago

or maybe use fork tc repo then CI auto mirror and test

**Comment by Rochet2** [comment]
Done. But I guess there is a need to take a look at that CI script on some day in the future and potentially move finally to GH actions from travis.

**Comment by Rochet2** [comment]
done and done
