### ISSUE TITLE
RegisterCreatureEvent is broken for Azerothcore

### ISSUE THREAD

**Issue by 55Honey** [ElunaLuaEngine/Eluna#367]
With the following code the onEnterCombat and onReset events never fire:
Just type a non-existant command to trigger it, e.g. `.ab`

```LUA
function command(event, player, command)

    local x = player:GetX()
    local y = player:GetY()
    local z = player:GetZ()
    local o = player:GetO()

    spawnedCreature = player:SpawnCreature(8905, x, y, z, o)

    RegisterCreatureEvent(8905, 1, onEnterCombat)
    RegisterCreatureEvent(8905, 2, onReset) -- OnLeaveCombat
    RegisterCreatureEvent(8905, 4, onReset) -- OnDied
end

function onEnterCombat(event, creature, target)
    print("enter combat fired")
end

function onReset(event, creature)
    print("reset fired")
end

RegisterPlayerEvent(PLAYER_EVENT_ON_COMMAND, command)
```

I suspect the recent unique GUID changes to be related: https://github.com/azerothcore/azerothcore-wotlk/pull/4885

Tested with:
- AzerothCore rev. 3716ddf3e4e1 2021-05-25 18:05:13 +0200 (master branch) (Win64, Release)
- mod-eluna-lua-engine https://github.com/azerothcore/mod-eluna-lua-engine/commit/10f5840d2fb063f9d9ca57af280b7bd2c61d8b99
- ElunaLuaEngine commit 2962d4fea3708cf22964d1cc750290b8980b313f and also the recent 9413bee27ae4dd8f305403d36a88113cd5945d33

**Comment by Rochet2** [comment]
Im fairly sure that has never worked.
The hooks are built into the AI class assigned to creatures.
The eluna AI class is not selected on spawn if there are no events registered for that creature.
So spawning the creature after registering should work.

Using the AI classes was convenient at the time, but it would be nice to get rid of using them to allow less restrictions and weird constraints on creatures.

I think a similar issue existed on arcemu. You basically usually need an AI event to be registered on a creature to register more AI events later on.

**Comment by 55Honey** [comment]
You're a genious. Thanks a lot.
I registered the events before the spawn and it worked.
