### ISSUE TITLE
Update to the latest Cmangos

### ISSUE THREAD

**Issue by magikzoro** [ElunaLuaEngine/Eluna#380]
can you upgrade to the latest [Cmangos wotlk](https://github.com/cmangos/mangos-wotlk)

**Comment by Rochet2** [comment]
Potentially fixed by https://github.com/ElunaLuaEngine/Eluna/pull/390
Im sure the build breaks with new changes in the future as well.
Also no idea if there is a core patch somewhere, is there @Niam5 ?

**Comment by Niam5** [comment]
I have the 3 patched cores for Vanilla, TBC, and WotLK under my username here. The Cmangos project team has made it clear that at this time they will not support the integration so for the time being I am maintaining it separate from the main project. I pull upstream changes when they come out but some have been breaking the auto merge so even if I published a git patch file it may break later down the road. I would be more then happy to publish a patch file if that is what is preferred or you can clone the desired repo and then get the the changes from it as I update it.

**Comment by Rochet2** [comment]
@Niam5 Nice. Btw. you can automatically get a diff by going to the [PR creation UI](https://github.com/cmangos/mangos-tbc/compare/master...Niam5:master) and then using .diff at the end of the url.
.patch is also a possibility, but it omits some data in case merge commits have changes or similar. So I dont recommend trying that.
Example:
https://github.com/cmangos/mangos-tbc/compare/master...Niam5:master.diff
https://github.com/cmangos/mangos-wotlk/compare/master...Niam5:master.diff
https://github.com/cmangos/mangos-classic/compare/master...Niam5:master.diff
This is especially easy as you have a fork, which allows github to work cross those two entirely different repos.
So in a way you already have published a patch :)

**Comment by Foereaper** [comment]
Readme now links to Niam5's forks, as they are actively maintained.
