### ISSUE TITLE
upgrade to latest tc wotlk

### ISSUE THREAD

**Issue by jasanhell1** [ElunaLuaEngine/Eluna#383]
Can you please update to the lastest tc wotlk
https://github.com/TrinityCore/TrinityCore/commit/7c7b4760d89f29b7ee3c2f15f94cd9be24dc36cb

I think the lastest ElunaTrinityWotlk cannot compile successfully.

**Comment by Rochet2** [comment]
Fixed in https://github.com/ElunaLuaEngine/Eluna/commit/33f9b264dbc1a8ace380a4cf0108b43e1fc74c5d
Also fixed auto merging for https://github.com/ElunaLuaEngine/ElunaTrinityWotlk

**Comment by jasanhell1** [comment]
Thank you!
