### ISSUE TITLE
PerformIngameSpawn

### ISSUE THREAD

**Issue by brannik** [ElunaLuaEngine/Eluna#386]
Hello im using AzerothCore 3.3.5 With Eluna module installed. Currently trying to spawn NPC from lua script. Since the script is triggered by the server not from player must use PerformIngameSpawn not SpawnCreature, anyway NPC dont appear at the location buuut when i restart worldserver is on proper location. How i can fix this ? xD

`NPC_SPWNED = PerformIngameSpawn(1,NPC_ID,map,0,x,y,z,o,0,0,1)`
Where all values are set in array ( will spawn NPC on random location) anyway thats not the problem..

**Comment by Rochet2** [comment]
It seems you are using `0` as the argument for `save` parameter. Note that in Lua any value except nil and false are true, so the parameter evaluates to true. This is why the NPC is probably saved and shows up on restart.

Passing nil as an argument to a parameter that has a default value will evaluate to the default value in Eluna.

Can you post more information about what mapid, instanceid, xyz coordinates and npc you try to use?
Knowing the mapid is important here for example as maps function differently.
It seems that for me using `PerformIngameSpawn(1,36,0,0,0,0,0,0,0,0,1)` seems to work as expected.
