### ISSUE TITLE
OnGossipSelect hook return false does not return to default action

### ISSUE THREAD

**Issue by anzz1** [ElunaLuaEngine/Eluna#404]
As per the docs, GOSSIP_EVENT_ON_SELECT should "Can return false to do default action." 
It does not work, at least not in TrinityCore-3.3.5. GossipHello works fine.

Example code:
```
-- 11867 = Woo Ping - Weapon Master - Stormwind
RegisterCreatureGossipEvent(11867, 1, function() return false end) -- GOSSIP_EVENT_ON_HELLO
RegisterCreatureGossipEvent(11867, 2, function() return false end) -- GOSSIP_EVENT_ON_SELECT
```

Test:
1. .go creature id 11867
2. Talk to the npc.
3. Hello works fine, default gossip menu comes up. Selecting an option does nothing.

If you change return of ON_HELLO to true, no menu comes up like it should happen. Changing ON_SELECT return value doesn't seem to have any effect and is always regarded as true (block default action)

Commit: https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/d53965c81d51cfb880aae6dac89705c6047f098d

**Comment by Rochet2** [comment]
> Changing ON_SELECT return value doesn't seem to have any effect and is always regarded as true (block default action)

What did you try to determine this?
When the gossip select script returns true, Woo ping does not open the weapon training menu nor does he open "What can other weapon masters teach?" when clicking them in the gossip menu.
So I cannot reproduce the issue at least on https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/39b474f1eb6dfe95cc9b5292c00a7ceb763207f5

**Comment by anzz1** [comment]
I tried it in different occasions wanting to be able to do exactly this:
"When gossip select returns false, then the gossip select handler for the selected action runs based on DB data or C++ script."

Specifically to this example, if you just use that example code as-is, you can talk to the Woo Ping NPC and get his default gossip options (meaning hello-return false works fine) but nothing happens on gossip select. I cannot open the weapon training nor the "What can other weapon masters teach?" menu options (meaning select-return false does not work)

**Comment by Rochet2** [comment]
Is it possible for you to debug this?
I am unable to reproduce this issue. Debugging resulted in the expected behavior being shown.

**Comment by anzz1** [comment]
Thanks for pointing me out to the right direction !

Simply by commenting out/removing all instances of `pPlayer->PlayerTalkClass->ClearMenus()` found in GossipHooks.cpp fixes the issue and now the select hook works properly ! Why it was even needed to call that in every single function, as there already is a Eluna func Player:GossipClearMenu() for that? 

I guess a fix should be pushed.

**Comment by anzz1** [comment]
And about the reproducing issue, here are the exact steps:
1. pull a clean https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/9c79b22b90f2efdf2a0bb30a7d809bbdfada1b47
2. compile (win x64, static, WITHOUT_METRICS)
3. add that aforementioned lua as test.lua in lua_scripts directory.
4. run the server, create a test account, make it gmlevel 3, create a lvl 1 human warrior, log in.
5. .go creature id 11867 , talk to him. even though both hooks return false, selecting an gossip option does nothing.

**Comment by anzz1** [comment]
I guess if you want to retain the functionality of auto-clearing the menu, to not have to call GossipClearMenu() on the lua-side of things, it should only be done if the hook returns "true". 

Doing ClearMenus() in GossipSelect/GossipHello probably makes the core think that the menu should be clear and there should be no options selectable and as a anti-bug/anti-hack measure it stops the execution path. 

In any case, if you want to retain original functionality and only parse the arguments (or just to "disable" the hook) by returning false, no additional functions should be called.

**Comment by Rochet2** [comment]
> Simply by commenting out/removing all instances of `pPlayer->PlayerTalkClass->ClearMenus()` found in GossipHooks.cpp fixes the issue

Ah yes. Clearing of the menu before its use. A classic.

> Why it was even needed to call that in every single function, as there already is a Eluna func Player:GossipClearMenu() for that?

The code is around 10 years old. Its a remnant from when the behavior of an older scripting engine was being emulated. In it clearing of the menus was not required in gossip hello nor in gossip select events.

> I guess if you want to retain the functionality of auto-clearing the menu, to not have to call GossipClearMenu() on the lua-side of things, it should only be done if the hook returns "true".

Indeed.
The issue is a bit unfortunate in the way that all existing scripts need to be changed to include the menu clearing if the function call is removed. However, not fixing the issue means that the intended behavior is broken.
We can probably keep the old behavior and fix the issue, but that requires a workaround where the hook stores the menu data, executes Lua, and then restores the menu data if the hook returned false. That isn't really clean.

I created a PR for now that fixes the issue, feel free to comment on it.
