### ISSUE TITLE
[Request] Creature:RemoveFromWorld

### ISSUE THREAD

**Issue by anzz1** [ElunaLuaEngine/Eluna#407]
Just like GameObject:RemoveFromWorld( deleteFromDB )
http://elunaluaengine.github.io/GameObject/RemoveFromWorld.html

but for Creatures. Currently you can PerformIngameSpawn and spawn permanent gameobjects and creatures, but can only remove gameobjects. for creatures have to use a blocking db query.

**Comment by iThorgrim** [comment]
@anzz1 -> https://github.com/iThorgrim/Eluna/commit/a93f8dadab7c134c48605c3e3316f1488ce4aa79
