### ISSUE TITLE
It cant support Tc master branch

### ISSUE THREAD

**Issue by xuehyc** [ElunaLuaEngine/Eluna#414]
am i correct？the orignal one

**Comment by xuehyc** [comment]
TrinityCore Open Source MMO Framework master = 9.2.0.42560 now

**Comment by xuehyc** [comment]
https://github.com/TrinityCore/TrinityCore

**Comment by Rochet2** [comment]
TC master branch is not supported.
https://github.com/ElunaLuaEngine/Eluna/issues/398#issuecomment-994079256
