### ISSUE TITLE
I could not found a Lua_scripts folder after finishi compiling

### ISSUE THREAD

**Issue by orangemallen** [ElunaLuaEngine/Eluna#415]
after I finish all the work by following the Installation step by step with core "https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.git"
but finally I could not found a folder named "Lua_scripts".
any one have suggests to help me
![89bb88b50e30d86fa8025c7df0b6237](https://user-images.githubusercontent.com/101910701/159101503-fe027042-fbb4-4727-a795-24482622971c.png)
?

**Comment by orangemallen** [comment]
I did see any changes after  I use the command "git submodule init" and "git submodule update".

**Comment by Rochet2** [comment]
Compiling https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/043a36a871186d3e735dbd6bc8988f5536fcb97a worked fine and produced lua_scripts folder.
How exactly did you get the source code you used to compile? Were there any errors?

If there is no `lua_scripts` folder then as a last resort it is possible for you to create the folder and then copy the extensions folder from https://github.com/ElunaLuaEngine/Eluna/tree/master/extensions into it.

**Comment by orangemallen** [comment]
> 

thank you Sir,
I got the source code by git.
I recompile it and the folder was at there.
so, maybe I deleted it ......
how ever thank you!
