### ISSUE TITLE
PLAYER_EVENT_ON_LEVEL_CHANGE error

### ISSUE THREAD

**Issue by Yuhenan** [ElunaLuaEngine/Eluna#417]
Hello, this PLAYER_EVENT_ON_LEVEL_CHANGE doesn't work --vanilla bropack v20

**Comment by Rochet2** [comment]
Is that mangos or cmangos or something else?

**Comment by Yuhenan** [comment]
> 那是芒果还是芒果还是别的什么？

TY...Is  VMANGOS

**Comment by Foereaper** [comment]
We don't support repacks, nor do we officially support vmangos. This has to be reported there if it's still an issue.
