### ISSUE TITLE
RegisterBGEvent - bg:GetMap(), (nil) missing metatable

### ISSUE THREAD

**Issue by PerfectlyFineCode** [ElunaLuaEngine/Eluna#426]
As title mentions, upon the callback of RegisterBGEvent, if you try to get the bg's map you will get (nil) missing metatable.

Am I doing something wrong?

```lua
function start(event, bg, bgId, instanceId)
    -- get players in the battleground
    local map = bg:GetMap()

    PrintInfo(map)
end

RegisterBGEvent(1, start)
```

**Comment by Rochet2** [comment]
What core are you using?

**Comment by PerfectlyFineCode** [comment]
> What core are you using? (TC, AC, mangos, cmangos, ...)

Tried with both Azerothcore and Trinitycore from various versions, same result.

**Comment by Rochet2** [comment]
The issue seems to be that GetMap in C++ returns a BattlegroundMap which is not supported/implemented.
However, it is just a derivative of Map.
This should fix it and makes the function return a Map as it is expected to according to Eluna documentation. https://github.com/ElunaLuaEngine/Eluna/commit/2eb527509051761f673d8b620b0dfdd81101787c

**Comment by PerfectlyFineCode** [comment]
> The issue seems to be that GetMap in C++ returns a BattlegroundMap which is not supported/implemented. However, it is just a derivative of Map. This should fix it and makes the function return a Map as it is expected to according to Eluna documentation. [2eb5275](https://github.com/ElunaLuaEngine/Eluna/commit/2eb527509051761f673d8b620b0dfdd81101787c)

Unfortunately doesn't work.
it returns (null) missing metatable now, and not (nil) missing metatable.

![image](https://user-images.githubusercontent.com/70201838/181765639-028e6bb1-8974-4523-9392-2f9270ca7cc0.png)

**Comment by Rochet2** [comment]
> Unfortunately doesn't work.
> at least it doesn't crash now which is a bonus, but it still doesn't work.

Are you still having the issue?
If you are using azerothcore, they need to pull the latest changes to their eluna module (https://github.com/azerothcore/mod-eluna)
On TC it should not occur if latest eluna is used.

> it returns (null) missing metatable now, and not (nil) missing metatable.

I think that originally the error message was saying null, so the error probably did not change.
