### ISSUE TITLE
The following error occurred while compiling the eluna module

### ISSUE THREAD

**Issue by dudemin** [ElunaLuaEngine/Eluna#437]
[ 27%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_player_settings.cpp.o
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h: In function ‘std::string httplib::detail::MD5(const string&)’:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:37: warning: ‘int MD5_Init(MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |                                     ^~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
      |                           ^~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:47: warning: ‘int MD5_Update(MD5_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |                                               ^~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:59: warning: ‘int MD5_Final(unsigned char*, MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |                                                           ^~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
      |                           ^~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:33: warning: ‘int MD5_Init(MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3976 |                                  MD5_DIGEST_LENGTH);
      |                                  ~~~~~~~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:49:27: note: declared here
   49 | OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
      |                           ^~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:33: warning: ‘int MD5_Update(MD5_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3976 |                                  MD5_DIGEST_LENGTH);
      |                                  ~~~~~~~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:50:27: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
      |                           ^~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3975:33: warning: ‘int MD5_Final(unsigned char*, MD5_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3975 |   return message_digest<MD5_CTX>(s, MD5_Init, MD5_Update, MD5_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3976 |                                  MD5_DIGEST_LENGTH);
      |                                  ~~~~~~~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:211,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/md5.h:51:27: note: declared here
   51 | OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
      |                           ^~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h: In function ‘std::string httplib::detail::SHA_256(const string&)’:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:40: warning: ‘int SHA256_Init(SHA256_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                        ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:73:27: note: declared here
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:53: warning: ‘int SHA256_Update(SHA256_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                                     ^~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:74:27: note: declared here
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:68: warning: ‘int SHA256_Final(unsigned char*, SHA256_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                                                    ^~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:76:27: note: declared here
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:36: warning: ‘int SHA256_Init(SHA256_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3981 |                                     SHA256_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:73:27: note: declared here
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:36: warning: ‘int SHA256_Update(SHA256_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3981 |                                     SHA256_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:74:27: note: declared here
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3980:36: warning: ‘int SHA256_Final(unsigned char*, SHA256_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3980 |   return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3981 |                                     SHA256_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:76:27: note: declared here
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h: In function ‘std::string httplib::detail::SHA_512(const string&)’:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:40: warning: ‘int SHA512_Init(SHA512_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |                                        ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:123:27: note: declared here
  123 | OSSL_DEPRECATEDIN_3_0 int SHA512_Init(SHA512_CTX *c);
      |                           ^~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:53: warning: ‘int SHA512_Update(SHA512_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |                                                     ^~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:124:27: note: declared here
  124 | OSSL_DEPRECATEDIN_3_0 int SHA512_Update(SHA512_CTX *c,
      |                           ^~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:68: warning: ‘int SHA512_Final(unsigned char*, SHA512_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |                                                                    ^~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:126:27: note: declared here
  126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md, SHA512_CTX *c);
      |                           ^~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:36: warning: ‘int SHA512_Init(SHA512_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3986 |                                     SHA512_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:123:27: note: declared here
  123 | OSSL_DEPRECATEDIN_3_0 int SHA512_Init(SHA512_CTX *c);
      |                           ^~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:36: warning: ‘int SHA512_Update(SHA512_CTX*, const void*, size_t)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3986 |                                     SHA512_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:124:27: note: declared here
  124 | OSSL_DEPRECATEDIN_3_0 int SHA512_Update(SHA512_CTX *c,
      |                           ^~~~~~~~~~~~~
In file included from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:3985:36: warning: ‘int SHA512_Final(unsigned char*, SHA512_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 3985 |   return message_digest<SHA512_CTX>(s, SHA512_Init, SHA512_Update, SHA512_Final,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 3986 |                                     SHA512_DIGEST_LENGTH);
      |                                     ~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/libs/httplib.h:212,
                 from /root/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/HttpManager.cpp:11:
/usr/include/openssl/sha.h:126:27: note: declared here
  126 | OSSL_DEPRECATEDIN_3_0 int SHA512_Final(unsigned char *md, SHA512_CTX *c);

**Comment by dudemin** [comment]
The version of Open_ SSL is 3.02.

**Comment by Rochet2** [comment]
Looks like this file should be updated:
https://github.com/azerothcore/mod-eluna/blob/1abf24490e15c25b66b98e8f89da262be157bed0/src/LuaEngine/libs/httplib.h

The issue was fixed in https://github.com/yhirose/cpp-httplib/commit/0857eba17b9d3ef90d45950f9853b7579d6a7f29

I assume copy pasting latest code from this is enough:
https://github.com/yhirose/cpp-httplib/blob/master/httplib.h

@r-o-b-o-t-o @55Honey

**Comment by r-o-b-o-t-o** [comment]
Thanks for the heads-up!

By the way @dudemin, issues for the AzerothCore fork of Eluna should go to https://github.com/azerothcore/mod-eluna
