### ISSUE TITLE
Elunaengine not loading scripts when compiled

### ISSUE THREAD

**Issue by stefan4444333** [ElunaLuaEngine/Eluna#443]
Hello, as of yesterday's date, when i was trying to compile a fresh ElunaTrinityWoltk server, i have an issue. I follow every step from the trinity installation guide and with every other core it works, but when i try to compile elunatrinitycore i stumble on a problem, to be more exact this:
![image](https://github.com/ElunaLuaEngine/Eluna/assets/142721332/b9fc6087-55a5-41c8-80cf-af1d8071daa6)
In the LuaEngine.cpp. As i have read the code it is just some checks to see if the file is hidden, so i deleted it and the compilation worked and everything was built. But when i start my server i get this 
![image](https://github.com/ElunaLuaEngine/Eluna/assets/142721332/25a85d18-82f2-47cd-bfad-21a6b88d76b2)
Which is odd but i haven't thought anything about it, but the problem is when i try to load lua scripts, it doesn't load or show they have been loaded * since i have added some checks on most of my scripts to be sure that they have all loaded *. Can this be an issue from my side or is this an issue with elunaengine for trinitycore?

**Comment by Rochet2** [comment]
The compilation error should now be fixed.

However, the issue with scripts and prints not working needs to be looked at.
TC made a few refactorings and changes recently that may have broken something on our side.

**Comment by stefan4444333** [comment]
I think they said to me what the problem was, instead of using %u, they use {} to print, or thats what i think it is

**Comment by Foereaper** [comment]
https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/aaa6e73c8ca6d60e943cb964605536eb78219db2

Commit that changed how strings are formatted. We either need to change the macro or we need to ifdef the outputs in Eluna

**Comment by Rochet2** [comment]
Fixed in:
* https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/2cc932a4ec4b32899851de7070237fed5ccfe85d
* https://github.com/ElunaLuaEngine/Eluna/commit/12797aa7788d48a4a380a5f0b038d010d6cf1f33

Thanks for reporting.
