### ISSUE TITLE
Unit:GetFriendlyUnitsInRange( range ) not returning correct units

### ISSUE THREAD

**Issue by Maha225** [ElunaLuaEngine/Eluna#447]
Description: I did some testing in cmangos classic (latest from Niam5). It seems that the Unit:GetFriendlyUnitsInRange( range ) returns table of enemies and neutrals. Not friendlies.

![testCommand](https://github.com/ElunaLuaEngine/Eluna/assets/4172483/017be27d-7c19-4a02-bd21-5ce24c0bf1d9)
![testCommand_2](https://github.com/ElunaLuaEngine/Eluna/assets/4172483/363f5850-329b-4a8c-8fab-8af77269e2f6)

**Comment by Rochet2** [comment]
All of the cores seem to use AnyFriendlyUnitInObjectRangeCheck as expected:
* https://github.com/ElunaLuaEngine/Eluna/blob/46bed6d6be8ecdb7835fcc8305695839f49394d1/TrinityCore/UnitMethods.h#L1037
* https://github.com/ElunaLuaEngine/Eluna/blob/46bed6d6be8ecdb7835fcc8305695839f49394d1/CMangos/UnitMethods.h#L1019
* https://github.com/ElunaLuaEngine/Eluna/blob/46bed6d6be8ecdb7835fcc8305695839f49394d1/Mangos/UnitMethods.h#L1254

However, it looks like the core side implementation on cmangos classic is not checking for friendliness:
* trinitycore: https://github.com/TrinityCore/TrinityCore/blob/fe2da02cc65a4c549bfea5709d7655c367dca1e9/src/server/game/Grids/Notifiers/GridNotifiers.h#L1007
* cmangos classic: https://github.com/cmangos/mangos-classic/blob/eaa38a9fe61a77d6a50fa448414cb35fd4f09f7a/src/game/Grids/GridNotifiers.h#L994
* mangos zero (classic): https://github.com/mangoszero/server/blob/28425a37e2326c721191895590798f90013f2fe6/src/game/WorldHandlers/GridNotifiers.h#L868

So it looks like a core side issue for cmangos classic.
Though it could be possible to also make a custom searcher on our side, it should probably be fixed on cmangos side.

**Comment by Rochet2** [comment]
Looks like in [this commit](https://github.com/cmangos/mangos-classic/commit/d7ff7e15a2ccaa7be81a6776d312b90278975834) they for some reason renamed the old friendly searcher and made a new one that doesnt actually check for friendliness
![image](https://github.com/ElunaLuaEngine/Eluna/assets/468816/08ab4f78-e358-49ba-86c9-4b72a384e369)

**Comment by Maha225** [comment]
Oh it's on their end, well I am happy that you figured it out! Thank you!
