### ISSUE TITLE
RegisterPlayerEvent _ON_KILLED_BY_CREATURE

### ISSUE THREAD

**Issue by betayi** [ElunaLuaEngine/Eluna#451]
PLAYER_EVENT_ON_KILLED_BY_CREATURE      =     8,

It seems not triggered ( not print ) while player killed by creature
--[code example]--
function OnPlayerDie(event, killer, killed)
  print(killed:GetName().." killed")
end

RegisterPlayerEvent(8, OnPlayerDie)

other RegisterPlayerEvent works fine
at cmangostbc with LuaEngine@f8f97c55f79a7563c29b0a7c917babef96cdbe0c

**Comment by Niam5** [comment]
The core your having this issue with is CMaNGOS TBC right? If so ill look at since I'm the maintainer for those.

**Comment by Niam5** [comment]
Please update your source files to 5279f5709d4a75f1a32bfe3e9411367a7feb7bb6 and retest for me please.

**Comment by betayi** [comment]
yes, it works,tyvm!

**Comment by betayi** [comment]
this will make a core crash in sometimes #452

**Comment by Niam5** [comment]
Duplicate of #452
