### ISSUE TITLE
Latest build fails on Mangos

### ISSUE THREAD

**Issue by billy1arm** [ElunaLuaEngine/Eluna#494]
@Foereaper @Rochet2 
#include "Hooks.h" is not found in LuiEngine.h

Steps to reproduce:

1) clone github.com/MangosZero/server
2) update Eluna submodule to master
3) Compile.

**Comment by Niam5** [comment]
I likely know what this is, that file got moved compared to the structure MaNGOS is currently using. I can submit a PR for you.

**Comment by Niam5** [comment]
MaNGOS is also not multistate compatible. Unless you have that work done elsewhere.

**Comment by Niam5** [comment]
Fixed by a19a6afea98e9ed9a20b6f371a2905ad93b7d766
