### ISSUE TITLE
HandleStatModifier

### ISSUE THREAD

**Issue by Juggalo187** [ElunaLuaEngine/Eluna#495]
Azerothcore Eluna module has the HandleStatModifier function, can that be added to trinitycore eluna?

**Comment by Foereaper** [comment]
Not 1:1 no, but I can add some similar methods

**Comment by Foereaper** [comment]
The above commit adds the following methods for TC:

https://elunaluaengine.github.io/Unit/CanModifyStats.html
https://elunaluaengine.github.io/Unit/AddFlatStatModifier.html
https://elunaluaengine.github.io/Unit/AddPctStatModifier.html

**Comment by Juggalo187** [comment]
Thanks, I had to manually apply it to ElunaTrinityWotlk but it works great.

I needed it for this script I've been wanting to make that I call Dungeonstats, when you kill a boss or optionally elites you gain a random stat.
