### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by PangciPG** [ElunaLuaEngine/Eluna#500]
The CMakeLists.txt in `ElunaTrinityWotlk/src/server/game/LuaEngine` not exist!
cmake report
```
CMake Error at src/server/game/CMakeLists.txt:128 (add_subdirectory):
  The source directory

    /home/trinity/ElunaTrinityWotlk/src/server/game/LuaEngine

  does not contain a CMakeLists.txt file.
```

**Comment by Foereaper** [comment]
Did you make sure to use ```--recurse``` when cloning the repo? Otherwise it won't pull the Eluna submodule.

Either way, run the following commands from the ElunaTrinityWotlk directory

```
git submodule init
git submodule update
```
then re-run cmake
