### ISSUE TITLE
Multivendor

### ISSUE THREAD

**Issue by Rochet2** [ElunaLuaEngine/Eluna#74]
Possible implementation of multivendor core modification.
Need mangos code.

http://rochet2.github.io/?page=Multivendor

**Comment by Asandru** [comment]
Yes the code allows multivendor by non creature gossip too

**Comment by Asandru** [comment]
Rewrote the patch.
Please notice, the patch allows the object sender to be an item, player, creature or even gameobject.
Patch: http://pastebin.com/5ZjS9pDL

Lua example: (player:SendListInventory(player, 4) where 4 is the vendor template id, if left 0 will send default vendor items)

local function OnTestCommands(event, player, msg, Type, lang)
    if (msg == "#test") then
        player:SendListInventory(player, 4)
        return false
    end
end

RegisterPlayerEvent(18, OnTestCommands)
