### ISSUE TITLE
Movement methods

### ISSUE THREAD

**Issue by Salja** [ElunaLuaEngine/Eluna#80]
http://emudevs.com/showthread.php/2235-Movement-Hooks
Already being worked on:
https://github.com/tyraela/ElunaCoreTbc/commits/master

Original https://github.com/ElunaLuaEngine/ElunaMangosWotlk/issues/19

**Comment by Rochet2** [comment]
Getter implemented on mangos and TC as requested.
If further additions or changes to movement methods needed open a new ticket.
