### ISSUE TITLE
support for eluna auctionhouse hooks

### ISSUE THREAD

**Issue by Salja** [ElunaLuaEngine/Eluna#81]
need support for eluna auctionhouse hooks

```
// Auction house
AUCTION_EVENT_ON_ADD                    =     65,       // Not Implemented
AUCTION_EVENT_ON_REMOVE                 =     66,       // Not Implemented
AUCTION_EVENT_ON_SUCCESFUL              =     67,       // Not Implemented
AUCTION_EVENT_ON_EXPIRE                 =     68,       // Not Implemented
```

AUCTION_EVENT_ON_SUCCESFUL
AUCTION_EVENT_ON_EXPIRE

is missing other done in commit https://github.com/eluna-dev-mangos/ElunaCoreWotlk/commit/7e1f444a412fb9f21eaa9c3fece2b1bda705877b

Original https://github.com/ElunaLuaEngine/ElunaMangosWotlk/issues/13

**Comment by Rochet2** [comment]
I believe this has been implemented on almost all cores.
Just some fine tuning needed.
